package co.zimly.bytrain.model

// TODO: Consider using a HashMap for station data
data class Station(val code: String, val name: String)

val allStations: List<Station> = listOf(
    Station("ABW", "Abbey Wood"),
    Station("ABE", "Aber"),
    Station("ACY", "Abercynon"),
    Station("ABA", "Aberdare"),
    Station("ABD", "Aberdeen"),
    Station("AUR", "Aberdour"),
    Station("AVY", "Aberdovey"),
    Station("ABH", "Abererch"),
    Station("AGV", "Abergavenny"),
    Station("AGL", "Abergele & Pensarn"),
    Station("AYW", "Aberystwyth"),
    Station("ACR", "Accrington"),
    Station("AAT", "Achanalt"),
    Station("ACN", "Achnasheen"),
    Station("ACH", "Achnashellach"),
    Station("ACK", "Acklington"),
    Station("ACL", "Acle"),
    Station("ACG", "Acocks Green"),
    Station("ACB", "Acton Bridge (Cheshire)"),
    Station("ACC", "Acton Central"),
    Station("AML", "Acton Main Line"),
    Station("ADD", "Adderley Park"),
    Station("ADW", "Addiewell"),
    Station("ASN", "Addlestone"),
    Station("ADM", "Adisham"),
    Station("ADC", "Adlington (Cheshire)"),
    Station("ADL", "Adlington (Lancs)"),
    Station("AWK", "Adwick"),
    Station("AIG", "Aigburth"),
    Station("ANS", "Ainsdale"),
    Station("AIN", "Aintree"),
    Station("AIR", "Airbles"),
    Station("ADR", "Airdrie"),
    Station("AYP", "Albany Park"),
    Station("ALB", "Albrighton"),
    Station("ALD", "Alderley Edge"),
    Station("AMT", "Aldermaston"),
    Station("AHT", "Aldershot"),
    Station("AGT", "Aldrington"),
    Station("AAP", "Alexandra Palace"),
    Station("AXP", "Alexandra Parade"),
    Station("ALX", "Alexandria"),
    Station("ALF", "Alfreton"),
    Station("ALW", "Allens West"),
    Station("ALO", "Alloa"),
    Station("ASS", "Alness"),
    Station("ALM", "Alnmouth"),
    Station("ALR", "Alresford (Essex)"),
    Station("ASG", "Alsager"),
    Station("ALN", "Althorne (Essex)"),
    Station("ALP", "Althorpe"),
    Station("ABC", "Altnabreac"),
    Station("AON", "Alton"),
    Station("ALT", "Altrincham"),
    Station("ALV", "Alvechurch"),
    Station("AMB", "Ambergate"),
    Station("AMY", "Amberley"),
    Station("AMR", "Amersham"),
    Station("AMF", "Ammanford"),
    Station("ANC", "Ancaster"),
    Station("AND", "Anderston"),
    Station("ADV", "Andover"),
    Station("ANZ", "Anerley"),
    Station("ANG", "Angmering"),
    Station("ANN", "Annan"),
    Station("ANL", "Anniesland"),
    Station("AFV", "Ansdell & Fairhaven"),
    Station("APY", "Apperley Bridge"),
    Station("APP", "Appleby"),
    Station("APD", "Appledore (Kent)"),
    Station("APF", "Appleford"),
    Station("APB", "Appley Bridge"),
    Station("APS", "Apsley"),
    Station("ARB", "Arbroath"),
    Station("ARD", "Ardgay"),
    Station("AUI", "Ardlui"),
    Station("ADS", "Ardrossan Harbour"),
    Station("ASB", "Ardrossan South Beach"),
    Station("ADN", "Ardrossan Town"),
    Station("ADK", "Ardwick"),
    Station("AGS", "Argyle Street"),
    Station("ARG", "Arisaig"),
    Station("ARL", "Arlesey"),
    Station("ARM", "Armadale (West Lothian)"),
    Station("AWT", "Armathwaite"),
    Station("ARN", "Arnside"),
    Station("ARR", "Arram"),
    Station("ART", "Arrochar & Tarbet"),
    Station("ARU", "Arundel"),
    Station("ACT", "Ascot (Berks)"),
    Station("AUW", "Ascott-under-Wychwood"),
    Station("ASH", "Ash"),
    Station("AHV", "Ash Vale"),
    Station("ABY", "Ashburys"),
    Station("ASC", "Ashchurch for Tewkesbury"),
    Station("ASF", "Ashfield"),
    Station("AFS", "Ashford (Surrey)"),
    Station("AFK", "Ashford International"),
    Station("ASI", "Ashford International (Eurostar)"),
    Station("ASY", "Ashley"),
    Station("AHD", "Ashtead"),
    Station("AHN", "Ashton-under-Lyne"),
    Station("AHS", "Ashurst (Kent)"),
    Station("ANF", "Ashurst New Forest"),
    Station("AWM", "Ashwell & Morden"),
    Station("ASK", "Askam"),
    Station("ALK", "Aslockton"),
    Station("ASP", "Aspatria"),
    Station("APG", "Aspley Guise"),
    Station("AST", "Aston"),
    Station("ATH", "Atherstone"),
    Station("ATN", "Atherton"),
    Station("ATT", "Attadale"),
    Station("ATB", "Attenborough"),
    Station("ATL", "Attleborough"),
    Station("AUK", "Auchinleck"),
    Station("AUD", "Audley End"),
    Station("AUG", "Aughton Park"),
    Station("AVM", "Aviemore"),
    Station("AVF", "Avoncliff"),
    Station("AVN", "Avonmouth"),
    Station("AXM", "Axminster"),
    Station("AYS", "Aylesbury"),
    Station("AVP", "Aylesbury Vale Parkway"),
    Station("AYL", "Aylesford"),
    Station("AYH", "Aylesham"),
    Station("AYR", "Ayr"),
    Station("BAC", "Bache"),
    Station("BAJ", "Baglan"),
    Station("BAG", "Bagshot"),
    Station("BLD", "Baildon"),
    Station("BIO", "Baillieston"),
    Station("BAB", "Balcombe"),
    Station("BDK", "Baldock"),
    Station("BAL", "Balham"),
    Station("BHC", "Balloch"),
    Station("BSI", "Balmossie"),
    Station("BMB", "Bamber Bridge"),
    Station("BAM", "Bamford"),
    Station("BNV", "Banavie"),
    Station("BAN", "Banbury"),
    Station("BNG", "Bangor (Gwynedd)"),
    Station("BAH", "Bank Hall"),
    Station("BAD", "Banstead"),
    Station("BSS", "Barassie"),
    Station("ZBB", "Barbican"),
    Station("BLL", "Bardon Mill"),
    Station("BAR", "Bare Lane"),
    Station("BGI", "Bargeddie"),
    Station("BGD", "Bargoed"),
    Station("BKG", "Barking"),
    Station("BRT", "Barlaston"),
    Station("BMG", "Barming"),
    Station("BRM", "Barmouth"),
    Station("BNH", "Barnehurst"),
    Station("BNS", "Barnes"),
    Station("BNI", "Barnes Bridge"),
    Station("BTB", "Barnetby"),
    Station("BAA", "Barnham"),
    Station("BNL", "Barnhill"),
    Station("BNY", "Barnsley"),
    Station("BNP", "Barnstaple"),
    Station("BTG", "Barnt Green"),
    Station("BRR", "Barrhead"),
    Station("BRL", "Barrhill"),
    Station("BAV", "Barrow Haven"),
    Station("BIF", "Barrow-in-Furness"),
    Station("BWS", "Barrow-Upon-Soar"),
    Station("BRY", "Barry"),
    Station("BYD", "Barry Docks"),
    Station("BYI", "Barry Island"),
    Station("BYL", "Barry Links"),
    Station("BAU", "Barton-on-Humber"),
    Station("BSO", "Basildon"),
    Station("BSK", "Basingstoke"),
    Station("BBL", "Bat & Ball"),
    Station("BTH", "Bath Spa"),
    Station("BHG", "Bathgate"),
    Station("BTL", "Batley"),
    Station("BTT", "Battersby"),
    Station("BAK", "Battersea Park"),
    Station("BAT", "Battle"),
    Station("BLB", "Battlesbridge"),
    Station("BAY", "Bayford"),
    Station("BCF", "Beaconsfield"),
    Station("BER", "Bearley"),
    Station("BRN", "Bearsden"),
    Station("BSD", "Bearsted"),
    Station("BSL", "Beasdale"),
    Station("BEU", "Beaulieu Road"),
    Station("BEL", "Beauly"),
    Station("BEB", "Bebington"),
    Station("BCC", "Beccles"),
    Station("BEC", "Beckenham Hill"),
    Station("BKJ", "Beckenham Junction"),
    Station("BDM", "Bedford"),
    Station("BSJ", "Bedford St Johns"),
    Station("BDH", "Bedhampton"),
    Station("BMT", "Bedminster"),
    Station("BEH", "Bedworth"),
    Station("BDW", "Bedwyn"),
    Station("BEE", "Beeston"),
    Station("BKS", "Bekesbourne"),
    Station("BLV", "Belle Vue"),
    Station("BLG", "Bellgrove"),
    Station("BGM", "Bellingham"),
    Station("BLH", "Bellshill"),
    Station("BLM", "Belmont"),
    Station("BLP", "Belper"),
    Station("BEG", "Beltring"),
    Station("BVD", "Belvedere"),
    Station("BEM", "Bempton"),
    Station("BEY", "Ben Rhydding"),
    Station("BEF", "Benfleet"),
    Station("BEN", "Bentham"),
    Station("BTY", "Bentley (Hants)"),
    Station("BYK", "Bentley (South Yorks)"),
    Station("BAS", "Bere Alston"),
    Station("BFE", "Bere Ferrers"),
    Station("BKM", "Berkhamsted"),
    Station("BKW", "Berkswell"),
    Station("BEP", "Bermuda Park"),
    Station("BYA", "Berney Arms"),
    Station("BBW", "Berry Brow"),
    Station("BRS", "Berrylands"),
    Station("BRK", "Berwick (Sussex)"),
    Station("BWK", "Berwick-upon-Tweed"),
    Station("BES", "Bescar Lane"),
    Station("BSC", "Bescot Stadium"),
    Station("BTO", "Betchworth"),
    Station("BET", "Bethnal Green"),
    Station("BYC", "Betws-y-Coed"),
    Station("BEV", "Beverley"),
    Station("BEX", "Bexhill"),
    Station("BXY", "Bexley"),
    Station("BXH", "Bexleyheath"),
    Station("BCS", "Bicester North"),
    Station("BIT", "Bicester Village"),
    Station("BKL", "Bickley"),
    Station("BID", "Bidston"),
    Station("BIW", "Biggleswade"),
    Station("BBK", "Bilbrook"),
    Station("BIC", "Billericay"),
    Station("BIL", "Billingham (Cleveland)"),
    Station("BIG", "Billingshurst"),
    Station("BIN", "Bingham"),
    Station("BIY", "Bingley"),
    Station("BCG", "Birchgrove"),
    Station("BCH", "Birchington-on-sea"),
    Station("BWD", "Birchwood"),
    Station("BIK", "Birkbeck"),
    Station("BDL", "Birkdale"),
    Station("BKC", "Birkenhead Central"),
    Station("BKQ", "Birkenhead Hamilton Square"),
    Station("BKN", "Birkenhead North"),
    Station("BKP", "Birkenhead Park"),
    Station("BHI", "Birmingham International"),
    Station("BMO", "Birmingham Moor Street"),
    Station("BHM", "Birmingham New Street"),
    Station("BSW", "Birmingham Snow Hill"),
    Station("BIA", "Bishop Auckland"),
    Station("BBG", "Bishopbriggs"),
    Station("BIS", "Bishops Stortford"),
    Station("BIP", "Bishopstone (Sussex)"),
    Station("BPT", "Bishopton (Strathclyde)"),
    Station("BTE", "Bitterne"),
    Station("BBN", "Blackburn"),
    Station("BKH", "Blackheath"),
    Station("BHO", "Blackhorse Road"),
    Station("BPN", "Blackpool North"),
    Station("BPB", "Blackpool Pleasure Beach"),
    Station("BPS", "Blackpool South"),
    Station("BKR", "Blackridge"),
    Station("BLK", "Blackrod"),
    Station("BAW", "Blackwater"),
    Station("BFF", "Blaenau Ffestiniog"),
    Station("BLA", "Blair Atholl"),
    Station("BAI", "Blairhill"),
    Station("BKT", "Blake Street"),
    Station("BKD", "Blakedown"),
    Station("BLT", "Blantyre"),
    Station("BLO", "Blaydon"),
    Station("BSB", "Bleasby"),
    Station("BLY", "Bletchley"),
    Station("BLX", "Bloxwich"),
    Station("BWN", "Bloxwich North"),
    Station("BLN", "Blundellsands & Crosby"),
    Station("BYB", "Blythe Bridge"),
    Station("BOD", "Bodmin Parkway"),
    Station("BOR", "Bodorgan"),
    Station("BOG", "Bognor Regis"),
    Station("BGS", "Bogston"),
    Station("BON", "Bolton"),
    Station("BTD", "Bolton-Upon-Dearne"),
    Station("BKA", "Bookham"),
    Station("BOC", "Bootle (Cumbria)"),
    Station("BNW", "Bootle New Strand"),
    Station("BOT", "Bootle Oriel Road"),
    Station("BBS", "Bordesley"),
    Station("BRG", "Borough Green & Wrotham"),
    Station("BRH", "Borth"),
    Station("BOH", "Bosham"),
    Station("BSN", "Boston"),
    Station("BOE", "Botley"),
    Station("BTF", "Bottesford"),
    Station("BNE", "Bourne End"),
    Station("BMH", "Bournemouth"),
    Station("BRV", "Bournville"),
    Station("BWB", "Bow Brickhill"),
    Station("BOP", "Bowes Park"),
    Station("BWG", "Bowling"),
    Station("BXW", "Box Hill & Westhumble"),
    Station("BCE", "Bracknell"),
    Station("BDQ", "Bradford Forster Square"),
    Station("BDI", "Bradford Interchange"),
    Station("BOA", "Bradford-on-Avon"),
    Station("BDN", "Brading"),
    Station("BTR", "Braintree"),
    Station("BTP", "Braintree Freeport"),
    Station("BML", "Bramhall"),
    Station("BMY", "Bramley (Hants)"),
    Station("BLE", "Bramley (W Yorks)"),
    Station("BMP", "Brampton (Cumbria)"),
    Station("BRP", "Brampton (Suffolk)"),
    Station("BCN", "Branchton"),
    Station("BND", "Brandon"),
    Station("BSM", "Branksome"),
    Station("BYS", "Braystones (Cumbria)"),
    Station("BDY", "Bredbury"),
    Station("BRC", "Breich"),
    Station("BFD", "Brentford"),
    Station("BRE", "Brentwood"),
    Station("BWO", "Bricket Wood"),
    Station("BEA", "Bridge of Allan"),
    Station("BRO", "Bridge of Orchy"),
    Station("BGN", "Bridgend"),
    Station("BDG", "Bridgeton"),
    Station("BWT", "Bridgwater"),
    Station("BDT", "Bridlington"),
    Station("BRF", "Brierfield"),
    Station("BGG", "Brigg"),
    Station("BGH", "Brighouse"),
    Station("BTN", "Brighton (East Sussex)"),
    Station("BMD", "Brimsdown"),
    Station("BNT", "Brinnington"),
    Station("BPW", "Bristol Parkway"),
    Station("BRI", "Bristol Temple Meads"),
    Station("BHD", "Brithdir"),
    Station("BNF", "Briton Ferry"),
    Station("BRX", "Brixton"),
    Station("BGE", "Broad Green"),
    Station("BDB", "Broadbottom"),
    Station("BSR", "Broadstairs"),
    Station("BCU", "Brockenhurst"),
    Station("BHS", "Brockholes"),
    Station("BCY", "Brockley"),
    Station("BOM", "Bromborough"),
    Station("BMR", "Bromborough Rake"),
    Station("BMC", "Bromley Cross (Lancs)"),
    Station("BMN", "Bromley North"),
    Station("BMS", "Bromley South"),
    Station("BMV", "Bromsgrove"),
    Station("BSY", "Brondesbury"),
    Station("BSP", "Brondesbury Park"),
    Station("BPK", "Brookmans Park"),
    Station("BKO", "Brookwood"),
    Station("BME", "Broome"),
    Station("BMF", "Broomfleet"),
    Station("BRA", "Brora"),
    Station("BUH", "Brough"),
    Station("BYF", "Broughty Ferry"),
    Station("BXB", "Broxbourne"),
    Station("BCV", "Bruce Grove"),
    Station("BDA", "Brundall"),
    Station("BGA", "Brundall Gardens"),
    Station("BSU", "Brunstane"),
    Station("BRW", "Brunswick"),
    Station("BRU", "Bruton"),
    Station("BYN", "Bryn"),
    Station("BUC", "Buckenham (Norfolk)"),
    Station("BCK", "Buckley"),
    Station("BUK", "Bucknell"),
    Station("BSV", "Buckshaw Parkway"),
    Station("BGL", "Bugle"),
    Station("BHR", "Builth Road"),
    Station("BLW", "Bulwell"),
    Station("BUE", "Bures"),
    Station("BUG", "Burgess Hill"),
    Station("BUY", "Burley Park"),
    Station("BUW", "Burley-in-Wharfedale"),
    Station("BNA", "Burnage"),
    Station("BUD", "Burneside (Cumbria)"),
    Station("BNM", "Burnham (Bucks)"),
    Station("BUU", "Burnham-on-Crouch"),
    Station("BUB", "Burnley Barracks"),
    Station("BNC", "Burnley Central"),
    Station("BYM", "Burnley Manchester Road"),
    Station("BUI", "Burnside (Strathclyde)"),
    Station("BTS", "Burntisland"),
    Station("BCB", "Burscough Bridge"),
    Station("BCJ", "Burscough Junction"),
    Station("BUO", "Bursledon"),
    Station("BUJ", "Burton Joyce"),
    Station("BUT", "Burton-on-Trent"),
    Station("BSE", "Bury St Edmunds"),
    Station("BUS", "Busby"),
    Station("BHK", "Bush Hill Park"),
    Station("BSH", "Bushey"),
    Station("BUL", "Butlers Lane"),
    Station("BXD", "Buxted"),
    Station("BUX", "Buxton"),
    Station("BFN", "Byfleet & New Haw"),
    Station("BYE", "Bynea"),
    Station("CAD", "Cadoxton"),
    Station("CGW", "Caergwrle"),
    Station("CPH", "Caerphilly"),
    Station("CWS", "Caersws"),
    Station("CAC", "Caldercruix"),
    Station("CDT", "Caldicot"),
    Station("CIR", "Caledonian Rd & Barnsbury"),
    Station("CSK", "Calstock"),
    Station("CDU", "Cam & Dursley"),
    Station("CAM", "Camberley"),
    Station("CBN", "Camborne"),
    Station("CBG", "Cambridge"),
    Station("CBH", "Cambridge Heath"),
    Station("CMB", "Cambridge North"),
    Station("CBL", "Cambuslang"),
    Station("CMD", "Camden Road"),
    Station("CMO", "Camelon"),
    Station("ZCW", "Canada Water"),
    Station("CNL", "Canley"),
    Station("CAO", "Cannock"),
    Station("CNN", "Canonbury"),
    Station("CBE", "Canterbury East"),
    Station("CBW", "Canterbury West"),
    Station("CNY", "Cantley"),
    Station("CPU", "Capenhurst"),
    Station("CBB", "Carbis Bay"),
    Station("CDD", "Cardenden"),
    Station("CDB", "Cardiff Bay"),
    Station("CDF", "Cardiff Central"),
    Station("CDQ", "Cardiff Queen Street"),
    Station("CDO", "Cardonald"),
    Station("CDR", "Cardross"),
    Station("CRF", "Carfin"),
    Station("CAK", "Cark & Cartmel"),
    Station("CAR", "Carlisle"),
    Station("CTO", "Carlton"),
    Station("CLU", "Carluke"),
    Station("CMN", "Carmarthen"),
    Station("CML", "Carmyle"),
    Station("CNF", "Carnforth"),
    Station("CAN", "Carnoustie"),
    Station("CAY", "Carntyne"),
    Station("CPK", "Carpenders Park"),
    Station("CAG", "Carrbridge"),
    Station("CSH", "Carshalton"),
    Station("CSB", "Carshalton Beeches"),
    Station("CRS", "Carstairs"),
    Station("CDY", "Cartsdyke"),
    Station("CBP", "Castle Bar Park"),
    Station("CLC", "Castle Cary"),
    Station("CFD", "Castleford"),
    Station("CAS", "Castleton (Manchester)"),
    Station("CSM", "Castleton Moor"),
    Station("CAT", "Caterham"),
    Station("CTF", "Catford"),
    Station("CFB", "Catford Bridge"),
    Station("CYS", "Cathays"),
    Station("CCT", "Cathcart"),
    Station("CTL", "Cattal"),
    Station("CAU", "Causeland"),
    Station("CYB", "Cefn-y-Bedd"),
    Station("CTH", "Chadwell Heath"),
    Station("CFH", "Chafford Hundred Lakeside"),
    Station("CFO", "Chalfont & Latimer"),
    Station("CHW", "Chalkwell"),
    Station("CFR", "Chandlers Ford"),
    Station("CEF", "Chapel-en-le-Frith"),
    Station("CPN", "Chapelton (Devon)"),
    Station("CLN", "Chapeltown (South Yorks)"),
    Station("CWC", "Chappel & Wakes Colne"),
    Station("CHG", "Charing (Kent)"),
    Station("CHC", "Charing Cross (Glasgow)"),
    Station("CBY", "Charlbury"),
    Station("CTN", "Charlton"),
    Station("CRT", "Chartham"),
    Station("CSR", "Chassen Road"),
    Station("CTE", "Chatelherault"),
    Station("CTM", "Chatham"),
    Station("CHT", "Chathill"),
    Station("CHU", "Cheadle Hulme"),
    Station("CHE", "Cheam"),
    Station("CED", "Cheddington"),
    Station("CEL", "Chelford (Cheshire)"),
    Station("CHM", "Chelmsford"),
    Station("CLD", "Chelsfield"),
    Station("CNM", "Cheltenham Spa"),
    Station("CPW", "Chepstow"),
    Station("CYT", "Cherry Tree"),
    Station("CHY", "Chertsey"),
    Station("CHN", "Cheshunt"),
    Station("CSN", "Chessington North"),
    Station("CSS", "Chessington South"),
    Station("CTR", "Chester"),
    Station("CRD", "Chester Road"),
    Station("CHD", "Chesterfield"),
    Station("CLS", "Chester-le-Street"),
    Station("CSW", "Chestfield & Swalecliffe"),
    Station("CNO", "Chetnole"),
    Station("CCH", "Chichester"),
    Station("CIL", "Chilham"),
    Station("CHL", "Chilworth"),
    Station("CHI", "Chingford"),
    Station("CLY", "Chinley"),
    Station("CPM", "Chippenham"),
    Station("CHP", "Chipstead"),
    Station("CRK", "Chirk"),
    Station("CIT", "Chislehurst"),
    Station("CHK", "Chiswick"),
    Station("CHO", "Cholsey"),
    Station("CRL", "Chorley"),
    Station("CLW", "Chorleywood"),
    Station("CHR", "Christchurch"),
    Station("CHH", "Christs Hospital"),
    Station("CTW", "Church & Oswaldtwistle"),
    Station("CHF", "Church Fenton"),
    Station("CTT", "Church Stretton"),
    Station("CIM", "Cilmeri"),
    Station("CTK", "City Thameslink"),
    Station("CLT", "Clacton-on-Sea"),
    Station("CLA", "Clandon"),
    Station("CPY", "Clapham (North Yorkshire)"),
    Station("CLP", "Clapham High Street"),
    Station("CLJ", "Clapham Junction"),
    Station("CPT", "Clapton"),
    Station("CLR", "Clarbeston Road"),
    Station("CKS", "Clarkston"),
    Station("CLV", "Claverdon"),
    Station("CLG", "Claygate"),
    Station("CLE", "Cleethorpes"),
    Station("CEA", "Cleland"),
    Station("CLI", "Clifton (Manchester)"),
    Station("CFN", "Clifton Down"),
    Station("CLH", "Clitheroe"),
    Station("CLK", "Clock House"),
    Station("CUW", "Clunderwen"),
    Station("CYK", "Clydebank"),
    Station("CBC", "Coatbridge Central"),
    Station("CBS", "Coatbridge Sunnyside"),
    Station("COA", "Coatdyke"),
    Station("CSD", "Cobham & Stoke d'Abernon"),
    Station("CSL", "Codsall"),
    Station("CGN", "Cogan"),
    Station("COL", "Colchester"),
    Station("CET", "Colchester Town"),
    Station("CEH", "Coleshill Parkway"),
    Station("CLM", "Collingham"),
    Station("CLL", "Collington"),
    Station("CNE", "Colne"),
    Station("CWL", "Colwall"),
    Station("CWB", "Colwyn Bay"),
    Station("CME", "Combe (Oxon)"),
    Station("COM", "Commondale"),
    Station("CNG", "Congleton"),
    Station("CNS", "Conisbrough"),
    Station("CON", "Connel Ferry"),
    Station("CBD", "Conon Bridge"),
    Station("CEY", "Cononley"),
    Station("CNP", "Conway Park"),
    Station("CNW", "Conwy"),
    Station("COB", "Cooden Beach"),
    Station("COO", "Cookham"),
    Station("CBR", "Cooksbridge"),
    Station("COE", "Coombe Junction Halt"),
    Station("COP", "Copplestone"),
    Station("CRB", "Corbridge"),
    Station("COR", "Corby"),
    Station("CFC", "Corfe Castle"),
    Station("CKH", "Corkerhill"),
    Station("CKL", "Corkickle"),
    Station("CPA", "Corpach"),
    Station("CRR", "Corrour"),
    Station("COY", "Coryton"),
    Station("CSY", "Coseley"),
    Station("COS", "Cosford"),
    Station("CSA", "Cosham"),
    Station("CGM", "Cottingham"),
    Station("COT", "Cottingley"),
    Station("CDS", "Coulsdon South"),
    Station("CDN", "Coulsdon Town"),
    Station("COV", "Coventry"),
    Station("CAA", "Coventry Arena"),
    Station("CWN", "Cowden (Kent)"),
    Station("COW", "Cowdenbeath"),
    Station("CRA", "Cradley Heath"),
    Station("CGD", "Craigendoran"),
    Station("CRM", "Cramlington"),
    Station("CBK", "Cranbrook (Devon)"),
    Station("CRV", "Craven Arms"),
    Station("CRW", "Crawley"),
    Station("CRY", "Crayford"),
    Station("CDI", "Crediton"),
    Station("CES", "Cressing (Essex)"),
    Station("CSG", "Cressington"),
    Station("CWD", "Creswell"),
    Station("CRE", "Crewe"),
    Station("CKN", "Crewkerne"),
    Station("CWH", "Crews Hill"),
    Station("CNR", "Crianlarich"),
    Station("CCC", "Criccieth"),
    Station("CRI", "Cricklewood"),
    Station("CFF", "Croftfoot"),
    Station("CFT", "Crofton Park"),
    Station("CMR", "Cromer"),
    Station("CMF", "Cromford"),
    Station("CKT", "Crookston"),
    Station("CRG", "Cross Gates"),
    Station("CFL", "Crossflatts"),
    Station("COI", "Crosshill"),
    Station("CKY", "Crosskeys"),
    Station("CMY", "Crossmyloof"),
    Station("CSO", "Croston"),
    Station("CRH", "Crouch Hill"),
    Station("COH", "Crowborough"),
    Station("CWU", "Crowhurst"),
    Station("CWE", "Crowle"),
    Station("CRN", "Crowthorne"),
    Station("CRO", "Croy"),
    Station("CYP", "Crystal Palace"),
    Station("CUD", "Cuddington"),
    Station("CUF", "Cuffley"),
    Station("CUM", "Culham"),
    Station("CUA", "Culrain"),
    Station("CUB", "Cumbernauld"),
    Station("CUP", "Cupar"),
    Station("CUH", "Curriehill"),
    Station("CUX", "Cuxton"),
    Station("CMH", "Cwmbach"),
    Station("CWM", "Cwmbran"),
    Station("CYN", "Cynghordy"),
    Station("DDK", "Dagenham Dock"),
    Station("DSY", "Daisy Hill"),
    Station("DAG", "Dalgety Bay"),
    Station("DAL", "Dalmally"),
    Station("DAK", "Dalmarnock"),
    Station("DAM", "Dalmeny"),
    Station("DMR", "Dalmuir"),
    Station("DLR", "Dalreoch"),
    Station("DLY", "Dalry"),
    Station("DLS", "Dalston (Cumbria)"),
    Station("DLJ", "Dalston Junction"),
    Station("DLK", "Dalston Kingsland"),
    Station("DLT", "Dalton (Cumbria)"),
    Station("DLW", "Dalwhinnie"),
    Station("DNY", "Danby"),
    Station("DCT", "Danescourt"),
    Station("DZY", "Danzey"),
    Station("DAR", "Darlington"),
    Station("DAN", "Darnall"),
    Station("DSM", "Darsham"),
    Station("DFD", "Dartford"),
    Station("DRT", "Darton"),
    Station("DWN", "Darwen"),
    Station("DAT", "Datchet"),
    Station("DVN", "Davenport"),
    Station("DWL", "Dawlish"),
    Station("DWW", "Dawlish Warren"),
    Station("DEA", "Deal"),
    Station("DEN", "Dean (Wilts)"),
    Station("DGT", "Deansgate"),
    Station("DGY", "Deganwy"),
    Station("DHN", "Deighton"),
    Station("DLM", "Delamere"),
    Station("DBD", "Denby Dale"),
    Station("DNM", "Denham"),
    Station("DGC", "Denham Golf Club"),
    Station("DMK", "Denmark Hill"),
    Station("DNT", "Dent"),
    Station("DTN", "Denton"),
    Station("DEP", "Deptford"),
    Station("DBY", "Derby"),
    Station("DBR", "Derby Road (Ipswich)"),
    Station("DPT", "Devonport (Devon)"),
    Station("DOC", "Devonport Dockyard"),
    Station("DEW", "Dewsbury"),
    Station("DID", "Didcot Parkway"),
    Station("DIG", "Digby & Sowton"),
    Station("DMH", "Dilton Marsh"),
    Station("DMG", "Dinas (Rhondda)"),
    Station("DNS", "Dinas Powys"),
    Station("DGL", "Dingle Road"),
    Station("DIN", "Dingwall"),
    Station("DND", "Dinsdale"),
    Station("DTG", "Dinting"),
    Station("DSL", "Disley"),
    Station("DIS", "Diss"),
    Station("DOD", "Dodworth"),
    Station("DOL", "Dolau"),
    Station("DLH", "Doleham"),
    Station("DLG", "Dolgarrog"),
    Station("DWD", "Dolwyddelan"),
    Station("DON", "Doncaster"),
    Station("DCH", "Dorchester South"),
    Station("DCW", "Dorchester West"),
    Station("DOR", "Dore & Totley"),
    Station("DKG", "Dorking (Main)"),
    Station("DPD", "Dorking Deepdene"),
    Station("DKT", "Dorking West"),
    Station("DMS", "Dormans"),
    Station("DDG", "Dorridge"),
    Station("DVH", "Dove Holes"),
    Station("DVP", "Dover Priory"),
    Station("DVC", "Dovercourt"),
    Station("DVY", "Dovey Junction"),
    Station("DOW", "Downham Market"),
    Station("DRG", "Drayton Green"),
    Station("DYP", "Drayton Park"),
    Station("DRM", "Drem"),
    Station("DRF", "Driffield"),
    Station("DRI", "Drigg"),
    Station("DTW", "Droitwich Spa"),
    Station("DRO", "Dronfield"),
    Station("DMC", "Drumchapel"),
    Station("DFR", "Drumfrochar"),
    Station("DRU", "Drumgelloch"),
    Station("DMY", "Drumry"),
    Station("DFP", "Dublin Ferryport"),
    Station("DPS", "Dublin Port - Stena"),
    Station("DUD", "Duddeston"),
    Station("DDP", "Dudley Port"),
    Station("DFI", "Duffield"),
    Station("DRN", "Duirinish"),
    Station("DST", "Duke Street"),
    Station("DUL", "Dullingham"),
    Station("DBC", "Dumbarton Central"),
    Station("DBE", "Dumbarton East"),
    Station("DUM", "Dumbreck"),
    Station("DMF", "Dumfries"),
    Station("DMP", "Dumpton Park"),
    Station("DUN", "Dunbar"),
    Station("DBL", "Dunblane"),
    Station("DCG", "Duncraig"),
    Station("DEE", "Dundee"),
    Station("DFL", "Dunfermline Queen Margaret"),
    Station("DFE", "Dunfermline Town"),
    Station("DKD", "Dunkeld & Birnam"),
    Station("DNL", "Dunlop"),
    Station("DNO", "Dunrobin Castle"),
    Station("DOT", "Dunston"),
    Station("DNG", "Dunton Green"),
    Station("DHM", "Durham"),
    Station("DUR", "Durrington-on-Sea"),
    Station("DYC", "Dyce"),
    Station("DYF", "Dyffryn Ardudwy"),
    Station("EAG", "Eaglescliffe"),
    Station("EAL", "Ealing Broadway"),
    Station("ERL", "Earlestown"),
    Station("EAR", "Earley"),
    Station("EAD", "Earlsfield"),
    Station("ELD", "Earlswood (Surrey)"),
    Station("EWD", "Earlswood (West Midlands)"),
    Station("ECR", "East Croydon"),
    Station("EDY", "East Didsbury"),
    Station("EDW", "East Dulwich"),
    Station("EFL", "East Farleigh"),
    Station("EGF", "East Garforth"),
    Station("EGR", "East Grinstead"),
    Station("EKL", "East Kilbride"),
    Station("EML", "East Malling"),
    Station("EMD", "East Midlands Parkway"),
    Station("ETL", "East Tilbury"),
    Station("EWR", "East Worthing"),
    Station("EBN", "Eastbourne"),
    Station("EBK", "Eastbrook"),
    Station("EST", "Easterhouse"),
    Station("ERA", "Eastham Rake"),
    Station("ESL", "Eastleigh"),
    Station("EGN", "Eastrington"),
    Station("EBD", "Ebbsfleet International"),
    Station("EBV", "Ebbw Vale Parkway"),
    Station("EBB", "Ebbw Vale Town"),
    Station("ECC", "Eccles (Manchester)"),
    Station("ECS", "Eccles Road"),
    Station("ECL", "Eccleston Park"),
    Station("EDL", "Edale"),
    Station("EDN", "Eden Park"),
    Station("EBR", "Edenbridge"),
    Station("EBT", "Edenbridge Town"),
    Station("EDG", "Edge Hill"),
    Station("EDB", "Edinburgh"),
    Station("EGY", "Edinburgh Gateway"),
    Station("EDP", "Edinburgh Park"),
    Station("EDR", "Edmonton Green"),
    Station("EFF", "Effingham Junction"),
    Station("EGG", "Eggesford"),
    Station("EGH", "Egham"),
    Station("EGT", "Egton"),
    Station("EPH", "Elephant & Castle"),
    Station("ZEL", "Elephant & Castle (Underground)"),
    Station("ELG", "Elgin"),
    Station("ELP", "Ellesmere Port"),
    Station("ELE", "Elmers End"),
    Station("ESD", "Elmstead Woods"),
    Station("ESW", "Elmswell"),
    Station("ELR", "Elsecar"),
    Station("ESM", "Elsenham (Essex)"),
    Station("ELS", "Elstree & Borehamwood"),
    Station("ELW", "Eltham"),
    Station("ELO", "Elton & Orston"),
    Station("ELY", "Ely"),
    Station("EMP", "Emerson Park"),
    Station("EMS", "Emsworth"),
    Station("ECP", "Energlyn & Churchill Park"),
    Station("ENC", "Enfield Chase"),
    Station("ENL", "Enfield Lock"),
    Station("ENF", "Enfield Town"),
    Station("ENT", "Entwistle"),
    Station("EPS", "Epsom (Surrey)"),
    Station("EPD", "Epsom Downs"),
    Station("ERD", "Erdington"),
    Station("ERI", "Eridge"),
    Station("ERH", "Erith"),
    Station("ESH", "Esher"),
    Station("EKB", "Eskbank"),
    Station("EXR", "Essex Road"),
    Station("ETC", "Etchingham"),
    Station("EBA", "Euxton Balshaw Lane"),
    Station("EVE", "Evesham"),
    Station("EWE", "Ewell East"),
    Station("EWW", "Ewell West"),
    Station("EXC", "Exeter Central"),
    Station("EXD", "Exeter St David's"),
    Station("EXT", "Exeter St Thomas"),
    Station("EXG", "Exhibition Centre (Glasgow)"),
    Station("EXM", "Exmouth"),
    Station("EXN", "Exton"),
    Station("EYN", "Eynsford"),
    Station("FRB", "Fairbourne"),
    Station("FRF", "Fairfield"),
    Station("FRL", "Fairlie"),
    Station("FRW", "Fairwater"),
    Station("FCN", "Falconwood"),
    Station("FKG", "Falkirk Grahamston"),
    Station("FKK", "Falkirk High"),
    Station("FOC", "Falls of Cruachan"),
    Station("FMR", "Falmer"),
    Station("FAL", "Falmouth Docks"),
    Station("FMT", "Falmouth Town"),
    Station("FRM", "Fareham"),
    Station("FNB", "Farnborough (Main)"),
    Station("FNN", "Farnborough North"),
    Station("FNC", "Farncombe"),
    Station("FNH", "Farnham"),
    Station("FNR", "Farningham Road"),
    Station("FNW", "Farnworth"),
    Station("ZFD", "Farringdon"),
    Station("FLD", "Fauldhouse"),
    Station("FAV", "Faversham"),
    Station("FGT", "Faygate"),
    Station("FAZ", "Fazakerley"),
    Station("FRN", "Fearn"),
    Station("FEA", "Featherstone"),
    Station("FLX", "Felixstowe"),
    Station("FEL", "Feltham"),
    Station("FNT", "Feniton"),
    Station("FEN", "Fenny Stratford"),
    Station("FER", "Fernhill"),
    Station("FRY", "Ferriby"),
    Station("FYS", "Ferryside"),
    Station("FFA", "Ffairfach"),
    Station("FIL", "Filey"),
    Station("FIT", "Filton Abbey Wood"),
    Station("FNY", "Finchley Road & Frognal"),
    Station("FPK", "Finsbury Park"),
    Station("FIN", "Finstock"),
    Station("FSB", "Fishbourne (Sussex)"),
    Station("FSG", "Fishersgate"),
    Station("FGW", "Fishguard & Goodwick"),
    Station("FGH", "Fishguard Harbour"),
    Station("FSK", "Fiskerton"),
    Station("FZW", "Fitzwilliam"),
    Station("FWY", "Five Ways"),
    Station("FLE", "Fleet"),
    Station("FLM", "Flimby"),
    Station("FLN", "Flint"),
    Station("FLT", "Flitwick"),
    Station("FLI", "Flixton"),
    Station("FLF", "Flowery Field"),
    Station("FKC", "Folkestone Central"),
    Station("FKW", "Folkestone West"),
    Station("FOD", "Ford"),
    Station("FOG", "Forest Gate"),
    Station("FOH", "Forest Hill"),
    Station("FBY", "Formby"),
    Station("FOR", "Forres"),
    Station("FRS", "Forsinard"),
    Station("FTM", "Fort Matilda"),
    Station("FTW", "Fort William"),
    Station("FOK", "Four Oaks"),
    Station("FOX", "Foxfield"),
    Station("FXN", "Foxton"),
    Station("FRT", "Frant"),
    Station("FTN", "Fratton"),
    Station("FRE", "Freshfield"),
    Station("FFD", "Freshford"),
    Station("FML", "Frimley"),
    Station("FRI", "Frinton-on-Sea"),
    Station("FZH", "Frizinghall"),
    Station("FRD", "Frodsham"),
    Station("FRO", "Frome"),
    Station("FLW", "Fulwell"),
    Station("FNV", "Furness Vale"),
    Station("FZP", "Furze Platt"),
    Station("GNB", "Gainsborough Central"),
    Station("GBL", "Gainsborough Lea Road"),
    Station("GAL", "Galashiels"),
    Station("GCH", "Garelochhead"),
    Station("GRF", "Garforth"),
    Station("GGV", "Gargrave"),
    Station("GAR", "Garrowhill"),
    Station("GRS", "Garscadden"),
    Station("GSD", "Garsdale"),
    Station("GSN", "Garston (Hertfordshire)"),
    Station("GSW", "Garswood"),
    Station("GRH", "Gartcosh"),
    Station("GMG", "Garth (Mid Glamorgan)"),
    Station("GTH", "Garth (Powys)"),
    Station("GVE", "Garve"),
    Station("GST", "Gathurst"),
    Station("GTY", "Gatley"),
    Station("GTW", "Gatwick Airport"),
    Station("GGJ", "Georgemas Junction"),
    Station("GER", "Gerrards Cross"),
    Station("GDP", "Gidea Park"),
    Station("GFN", "Giffnock"),
    Station("GIG", "Giggleswick"),
    Station("GBD", "Gilberdyke"),
    Station("GFF", "Gilfach Fargoed"),
    Station("GIL", "Gillingham (Dorset)"),
    Station("GLM", "Gillingham (Kent)"),
    Station("GSC", "Gilshochill"),
    Station("GIP", "Gipsy Hill"),
    Station("GIR", "Girvan"),
    Station("GLS", "Glaisdale"),
    Station("GCW", "Glan Conwy"),
    Station("GLC", "Glasgow Central"),
    Station("GLQ", "Glasgow Queen Street"),
    Station("GLH", "Glasshoughton"),
    Station("GLZ", "Glazebrook"),
    Station("GLE", "Gleneagles"),
    Station("GLF", "Glenfinnan"),
    Station("GLG", "Glengarnock"),
    Station("GLT", "Glenrothes with Thornton"),
    Station("GLO", "Glossop"),
    Station("GCR", "Gloucester"),
    Station("GLY", "Glynde"),
    Station("GOB", "Gobowen"),
    Station("GOD", "Godalming"),
    Station("GDL", "Godley"),
    Station("GDN", "Godstone"),
    Station("GOE", "Goldthorpe"),
    Station("GOF", "Golf Street"),
    Station("GOL", "Golspie"),
    Station("GOM", "Gomshall"),
    Station("GMY", "Goodmayes"),
    Station("GOO", "Goole"),
    Station("GTR", "Goostrey"),
    Station("GDH", "Gordon Hill"),
    Station("GBG", "Gorebridge"),
    Station("GOR", "Goring & Streatley"),
    Station("GBS", "Goring-by-Sea"),
    Station("GTO", "Gorton"),
    Station("GPO", "Gospel Oak"),
    Station("GRK", "Gourock"),
    Station("GWN", "Gowerton"),
    Station("GOX", "Goxhill"),
    Station("GPK", "Grange Park"),
    Station("GOS", "Grange-Over-Sands"),
    Station("GTN", "Grangetown (Cardiff)"),
    Station("GRA", "Grantham"),
    Station("GRT", "Grateley"),
    Station("GVH", "Gravelly Hill"),
    Station("GRV", "Gravesend"),
    Station("GRY", "Grays"),
    Station("GTA", "Great Ayton"),
    Station("GRB", "Great Bentley"),
    Station("GRC", "Great Chesterford"),
    Station("GCT", "Great Coates"),
    Station("GMV", "Great Malvern"),
    Station("GMN", "Great Missenden"),
    Station("GYM", "Great Yarmouth"),
    Station("GNL", "Green Lane"),
    Station("GNR", "Green Road"),
    Station("GBK", "Greenbank"),
    Station("GRL", "Greenfaulds"),
    Station("GNF", "Greenfield"),
    Station("GFD", "Greenford"),
    Station("GNH", "Greenhithe"),
    Station("GKC", "Greenock Central"),
    Station("GKW", "Greenock West"),
    Station("GNW", "Greenwich"),
    Station("GEA", "Gretna Green"),
    Station("GMD", "Grimsby Docks"),
    Station("GMB", "Grimsby Town"),
    Station("GRN", "Grindleford"),
    Station("GMT", "Grosmont"),
    Station("GRP", "Grove Park"),
    Station("GUI", "Guide Bridge"),
    Station("GLD", "Guildford"),
    Station("GSY", "Guiseley"),
    Station("GUN", "Gunnersbury"),
    Station("GSL", "Gunnislake"),
    Station("GNT", "Gunton"),
    Station("GWE", "Gwersyllt"),
    Station("GYP", "Gypsy Lane"),
    Station("HAB", "Habrough"),
    Station("HCB", "Hackbridge"),
    Station("HKC", "Hackney Central"),
    Station("HAC", "Hackney Downs"),
    Station("HKW", "Hackney Wick"),
    Station("HDM", "Haddenham & Thame Parkway"),
    Station("HAD", "Haddiscoe"),
    Station("HDF", "Hadfield"),
    Station("HDW", "Hadley Wood"),
    Station("HGF", "Hag Fold"),
    Station("HGG", "Haggerston"),
    Station("HAG", "Hagley"),
    Station("HMY", "Hairmyres"),
    Station("HAL", "Hale (Manchester)"),
    Station("HAS", "Halesworth"),
    Station("HED", "Halewood"),
    Station("HFX", "Halifax"),
    Station("HLG", "Hall Green"),
    Station("HLR", "Hall Road"),
    Station("HAI", "Halling"),
    Station("HID", "Hall-i'-th'-Wood"),
    Station("HWH", "Haltwhistle"),
    Station("HMT", "Ham Street"),
    Station("HME", "Hamble"),
    Station("HNC", "Hamilton Central"),
    Station("HNW", "Hamilton West"),
    Station("HMM", "Hammerton"),
    Station("HMD", "Hampden Park (Sussex)"),
    Station("HDH", "Hampstead Heath"),
    Station("HMP", "Hampton (London)"),
    Station("HMC", "Hampton Court"),
    Station("HMW", "Hampton Wick"),
    Station("HIA", "Hampton-in-Arden"),
    Station("HSD", "Hamstead (Birmingham)"),
    Station("HAM", "Hamworthy"),
    Station("HND", "Hanborough"),
    Station("HTH", "Handforth"),
    Station("HAN", "Hanwell"),
    Station("HPN", "Hapton"),
    Station("HRL", "Harlech"),
    Station("HDN", "Harlesden"),
    Station("HRD", "Harling Road"),
    Station("HLN", "Harlington (Beds)"),
    Station("HWM", "Harlow Mill"),
    Station("HWN", "Harlow Town"),
    Station("HRO", "Harold Wood"),
    Station("HPD", "Harpenden"),
    Station("HRM", "Harrietsham"),
    Station("HGY", "Harringay"),
    Station("HRY", "Harringay Green Lanes"),
    Station("HRR", "Harrington"),
    Station("HGT", "Harrogate"),
    Station("HRW", "Harrow & Wealdstone"),
    Station("HOH", "Harrow-on-the-Hill"),
    Station("HTF", "Hartford (Cheshire)"),
    Station("HBY", "Hartlebury"),
    Station("HPL", "Hartlepool"),
    Station("HTW", "Hartwood"),
    Station("HPQ", "Harwich International"),
    Station("HWC", "Harwich Town"),
    Station("HSL", "Haslemere"),
    Station("HSK", "Hassocks"),
    Station("HGS", "Hastings"),
    Station("HTE", "Hatch End"),
    Station("HFS", "Hatfield & Stainforth"),
    Station("HAT", "Hatfield (Herts)"),
    Station("HAP", "Hatfield Peverel"),
    Station("HSG", "Hathersage"),
    Station("HTY", "Hattersley"),
    Station("HTN", "Hatton"),
    Station("HAV", "Havant"),
    Station("HVN", "Havenhouse"),
    Station("HVF", "Haverfordwest"),
    Station("HWD", "Hawarden"),
    Station("HWB", "Hawarden Bridge"),
    Station("HKH", "Hawkhead"),
    Station("HDB", "Haydon Bridge"),
    Station("HYR", "Haydons Road"),
    Station("HAY", "Hayes & Harlington"),
    Station("HYS", "Hayes (Kent)"),
    Station("HYL", "Hayle"),
    Station("HYM", "Haymarket"),
    Station("HHE", "Haywards Heath"),
    Station("HAZ", "Hazel Grove"),
    Station("HCN", "Headcorn"),
    Station("HDY", "Headingley"),
    Station("HDL", "Headstone Lane"),
    Station("HDG", "Heald Green"),
    Station("HLI", "Healing"),
    Station("HHL", "Heath High Level"),
    Station("HLL", "Heath Low Level"),
    Station("HAF", "Heathrow Airport Terminal 4"),
    Station("HWV", "Heathrow Airport Terminal 5"),
    Station("HXX", "Heathrow Airport Terminals 1, 2 and 3"),
    Station("HTC", "Heaton Chapel"),
    Station("HBD", "Hebden Bridge"),
    Station("HEC", "Heckington"),
    Station("HDE", "Hedge End"),
    Station("HNF", "Hednesford"),
    Station("HEI", "Heighington"),
    Station("HLC", "Helensburgh Central"),
    Station("HLU", "Helensburgh Upper"),
    Station("HLD", "Hellifield"),
    Station("HMS", "Helmsdale"),
    Station("HSB", "Helsby"),
    Station("HML", "Hemel Hempstead"),
    Station("HEN", "Hendon"),
    Station("HNG", "Hengoed"),
    Station("HNL", "Henley-in-Arden"),
    Station("HOT", "Henley-on-Thames"),
    Station("HEL", "Hensall"),
    Station("HFD", "Hereford"),
    Station("HNB", "Herne Bay"),
    Station("HNH", "Herne Hill"),
    Station("HER", "Hersham"),
    Station("HFE", "Hertford East"),
    Station("HFN", "Hertford North"),
    Station("HES", "Hessle"),
    Station("HSW", "Heswall"),
    Station("HEV", "Hever"),
    Station("HEW", "Heworth"),
    Station("HEX", "Hexham"),
    Station("HYD", "Heyford"),
    Station("HHB", "Heysham Port"),
    Station("HIB", "High Brooms"),
    Station("HST", "High Street (Glasgow)"),
    Station("ZHS", "High Street Kensington Underground"),
    Station("HWY", "High Wycombe"),
    Station("HGM", "Higham (Kent)"),
    Station("HIP", "Highams Park"),
    Station("HIG", "Highbridge & Burnham"),
    Station("HHY", "Highbury & Islington"),
    Station("HTO", "Hightown"),
    Station("HLB", "Hildenborough"),
    Station("HLF", "Hillfoot"),
    Station("HLE", "Hillington East"),
    Station("HLW", "Hillington West"),
    Station("HIL", "Hillside"),
    Station("HLS", "Hilsea"),
    Station("HYW", "Hinchley Wood"),
    Station("HNK", "Hinckley (Leics)"),
    Station("HIN", "Hindley"),
    Station("HNA", "Hinton Admiral"),
    Station("HIT", "Hitchin"),
    Station("HGR", "Hither Green"),
    Station("HOC", "Hockley"),
    Station("HBN", "Hollingbourne"),
    Station("HCH", "Holmes Chapel"),
    Station("HLM", "Holmwood"),
    Station("HOL", "Holton Heath"),
    Station("HHD", "Holyhead"),
    Station("HLY", "Holytown"),
    Station("HMN", "Homerton"),
    Station("HYB", "Honeybourne"),
    Station("HON", "Honiton"),
    Station("HOY", "Honley"),
    Station("HPA", "Honor Oak Park"),
    Station("HOK", "Hook"),
    Station("HOO", "Hooton"),
    Station("HOP", "Hope (Derbyshire)"),
    Station("HPE", "Hope (Flintshire)"),
    Station("HPT", "Hopton Heath"),
    Station("HRE", "Horden"),
    Station("HOR", "Horley"),
    Station("HBP", "Hornbeam Park"),
    Station("HRN", "Hornsey"),
    Station("HRS", "Horsforth"),
    Station("HRH", "Horsham"),
    Station("HSY", "Horsley"),
    Station("HIR", "Horton-in-Ribblesdale"),
    Station("HWI", "Horwich Parkway"),
    Station("HSC", "Hoscar"),
    Station("HGN", "Hough Green"),
    Station("HOU", "Hounslow"),
    Station("HOV", "Hove"),
    Station("HXM", "Hoveton & Wroxham"),
    Station("HWW", "How Wood (Herts)"),
    Station("HOW", "Howden"),
    Station("HOZ", "Howwood (Renfrewshire)"),
    Station("HOX", "Hoxton"),
    Station("HYK", "Hoylake"),
    Station("HBB", "Hubberts Bridge"),
    Station("HKN", "Hucknall"),
    Station("HUD", "Huddersfield"),
    Station("HUL", "Hull"),
    Station("HUP", "Humphrey Park"),
    Station("HCT", "Huncoat"),
    Station("HGD", "Hungerford"),
    Station("HUB", "Hunmanby"),
    Station("HUN", "Huntingdon"),
    Station("HNT", "Huntly"),
    Station("HNX", "Hunts Cross"),
    Station("HUR", "Hurst Green"),
    Station("HUT", "Hutton Cranswick"),
    Station("HUY", "Huyton"),
    Station("HYC", "Hyde Central"),
    Station("HYT", "Hyde North"),
    Station("HKM", "Hykeham"),
    Station("HYN", "Hyndland"),
    Station("HYH", "Hythe (Essex)"),
    Station("IBM", "IBM"),
    Station("IFI", "Ifield"),
    Station("IFD", "Ilford"),
    Station("ILN", "Ilkeston"),
    Station("ILK", "Ilkley"),
    Station("IMW", "Imperial Wharf"),
    Station("INE", "Ince & Elton"),
    Station("INC", "Ince (Manchester)"),
    Station("INT", "Ingatestone"),
    Station("INS", "Insch"),
    Station("IGD", "Invergordon"),
    Station("ING", "Invergowrie"),
    Station("INK", "Inverkeithing"),
    Station("INP", "Inverkip"),
    Station("INV", "Inverness"),
    Station("INH", "Invershin"),
    Station("INR", "Inverurie"),
    Station("IPS", "Ipswich"),
    Station("IRL", "Irlam"),
    Station("IRV", "Irvine"),
    Station("ISL", "Isleworth"),
    Station("ISP", "Islip"),
    Station("IVR", "Iver"),
    Station("IVY", "Ivybridge"),
    Station("JCH", "James Cook"),
    Station("JEQ", "Jewellery Quarter"),
    Station("JOH", "Johnston (Pembs)"),
    Station("JHN", "Johnstone (Strathclyde)"),
    Station("JOR", "Jordanhill"),
    Station("KSL", "Kearsley (Manchester)"),
    Station("KSN", "Kearsney (Kent)"),
    Station("KEI", "Keighley"),
    Station("KEH", "Keith"),
    Station("KEL", "Kelvedon"),
    Station("KVD", "Kelvindale"),
    Station("KEM", "Kemble"),
    Station("KMH", "Kempston Hardwick"),
    Station("KMP", "Kempton Park Racecourse"),
    Station("KMS", "Kemsing"),
    Station("KML", "Kemsley"),
    Station("KEN", "Kendal"),
    Station("KNW", "Kenilworth"),
    Station("KLY", "Kenley"),
    Station("KNE", "Kennett"),
    Station("KNS", "Kennishead"),
    Station("KNL", "Kensal Green"),
    Station("KNR", "Kensal Rise"),
    Station("KPA", "Kensington Olympia"),
    Station("KTH", "Kent House"),
    Station("KTN", "Kentish Town"),
    Station("KTW", "Kentish Town West"),
    Station("KNT", "Kenton"),
    Station("KBK", "Kents Bank"),
    Station("KET", "Kettering"),
    Station("KWB", "Kew Bridge"),
    Station("KWG", "Kew Gardens"),
    Station("KEY", "Keyham"),
    Station("KYN", "Keynsham"),
    Station("KDB", "Kidbrooke"),
    Station("KID", "Kidderminster"),
    Station("KDG", "Kidsgrove"),
    Station("KWL", "Kidwelly"),
    Station("KBN", "Kilburn High Road"),
    Station("KLD", "Kildale"),
    Station("KIL", "Kildonan"),
    Station("KGT", "Kilgetty"),
    Station("KMK", "Kilmarnock"),
    Station("KLM", "Kilmaurs"),
    Station("KPT", "Kilpatrick"),
    Station("KWN", "Kilwinning"),
    Station("KBC", "Kinbrace"),
    Station("KGM", "Kingham"),
    Station("KGH", "Kinghorn"),
    Station("KGL", "Kings Langley"),
    Station("KLN", "Kings Lynn"),
    Station("KNN", "Kings Norton"),
    Station("KGN", "Kings Nympton"),
    Station("KGP", "Kings Park"),
    Station("KGS", "Kings Sutton"),
    Station("KGE", "Kingsknowe"),
    Station("KNG", "Kingston"),
    Station("KND", "Kingswood"),
    Station("KIN", "Kingussie"),
    Station("KIT", "Kintbury"),
    Station("KBX", "Kirby Cross"),
    Station("KKS", "Kirk Sandall"),
    Station("KIR", "Kirkby (Merseyside)"),
    Station("KSW", "Kirkby Stephen"),
    Station("KKB", "Kirkby-in-Ashfield"),
    Station("KBF", "Kirkby-in-Furness"),
    Station("KDY", "Kirkcaldy"),
    Station("KRK", "Kirkconnel"),
    Station("KKD", "Kirkdale"),
    Station("KKM", "Kirkham & Wesham"),
    Station("KKH", "Kirkhill"),
    Station("KKN", "Kirknewton"),
    Station("KLF", "Kirkstall Forge"),
    Station("KWD", "Kirkwood"),
    Station("KTL", "Kirton Lindsey"),
    Station("KIV", "Kiveton Bridge"),
    Station("KVP", "Kiveton Park"),
    Station("KNA", "Knaresborough"),
    Station("KBW", "Knebworth"),
    Station("KNI", "Knighton"),
    Station("KCK", "Knockholt"),
    Station("KNO", "Knottingley"),
    Station("KNU", "Knucklas"),
    Station("KNF", "Knutsford"),
    Station("KYL", "Kyle of Lochalsh"),
    Station("LDY", "Ladybank"),
    Station("LAD", "Ladywell"),
    Station("LAI", "Laindon"),
    Station("LRG", "Lairg"),
    Station("LKE", "Lake"),
    Station("LAK", "Lakenheath"),
    Station("LAM", "Lamphey"),
    Station("LNK", "Lanark"),
    Station("LAN", "Lancaster"),
    Station("LAC", "Lancing"),
    Station("LAW", "Landywood"),
    Station("LGB", "Langbank"),
    Station("LHO", "Langho"),
    Station("LNY", "Langley (Berks)"),
    Station("LGG", "Langley Green"),
    Station("LGM", "Langley Mill"),
    Station("LGS", "Langside"),
    Station("LGW", "Langwathby"),
    Station("LAG", "Langwith-Whaley Thorns"),
    Station("LAP", "Lapford"),
    Station("LPW", "Lapworth"),
    Station("LBT", "Larbert"),
    Station("LAR", "Largs"),
    Station("LRH", "Larkhall"),
    Station("LAU", "Laurencekirk"),
    Station("LWH", "Lawrence Hill"),
    Station("LAY", "Layton (Lancs)"),
    Station("LZB", "Lazonby & Kirkoswald"),
    Station("LEB", "Lea Bridge"),
    Station("LEG", "Lea Green"),
    Station("LEH", "Lea Hall"),
    Station("LEA", "Leagrave"),
    Station("LHM", "Lealholm"),
    Station("LMS", "Leamington Spa"),
    Station("LSW", "Leasowe"),
    Station("LHD", "Leatherhead"),
    Station("LED", "Ledbury"),
    Station("LEE", "Lee (London)"),
    Station("LDS", "Leeds"),
    Station("LEI", "Leicester"),
    Station("LIH", "Leigh (Kent)"),
    Station("LES", "Leigh-on-Sea"),
    Station("LBZ", "Leighton Buzzard"),
    Station("LEL", "Lelant"),
    Station("LTS", "Lelant Saltings"),
    Station("LEN", "Lenham"),
    Station("LNZ", "Lenzie"),
    Station("LEO", "Leominster"),
    Station("LET", "Letchworth Garden City"),
    Station("LEU", "Leuchars (for St. Andrews)"),
    Station("LVM", "Levenshulme"),
    Station("LWS", "Lewes"),
    Station("LEW", "Lewisham"),
    Station("LEY", "Leyland"),
    Station("LEM", "Leyton Midland Road"),
    Station("LER", "Leytonstone High Road"),
    Station("LIC", "Lichfield City"),
    Station("LTV", "Lichfield Trent Valley"),
    Station("LID", "Lidlington"),
    Station("LHS", "Limehouse"),
    Station("LCN", "Lincoln Central"),
    Station("LFD", "Lingfield"),
    Station("LGD", "Lingwood"),
    Station("LIN", "Linlithgow"),
    Station("LIP", "Liphook"),
    Station("LSK", "Liskeard"),
    Station("LIS", "Liss"),
    Station("LVT", "Lisvane & Thornhill"),
    Station("LTK", "Little Kimble"),
    Station("LTT", "Little Sutton"),
    Station("LTL", "Littleborough"),
    Station("LIT", "Littlehampton"),
    Station("LVN", "Littlehaven"),
    Station("LTP", "Littleport"),
    Station("LVC", "Liverpool Central"),
    Station("LVJ", "Liverpool James Street"),
    Station("LIV", "Liverpool Lime Street"),
    Station("LPY", "Liverpool South Parkway"),
    Station("LSN", "Livingston North"),
    Station("LVG", "Livingston South"),
    Station("LLA", "Llanaber"),
    Station("LBR", "Llanbedr"),
    Station("LLT", "Llanbister Road"),
    Station("LNB", "Llanbradach"),
    Station("LLN", "Llandaf"),
    Station("LDN", "Llandanwg"),
    Station("LLC", "Llandecwyn"),
    Station("LLL", "Llandeilo"),
    Station("LLV", "Llandovery"),
    Station("LLO", "Llandrindod"),
    Station("LLD", "Llandudno"),
    Station("LLJ", "Llandudno Junction"),
    Station("LLI", "Llandybie"),
    Station("LLE", "Llanelli"),
    Station("LLF", "Llanfairfechan"),
    Station("LPG", "Llanfairpwll"),
    Station("LLG", "Llangadog"),
    Station("LLM", "Llangammarch"),
    Station("LLH", "Llangennech"),
    Station("LGO", "Llangynllo"),
    Station("LLR", "Llanharan"),
    Station("LTH", "Llanhilleth"),
    Station("LLS", "Llanishen"),
    Station("LWR", "Llanrwst"),
    Station("LAS", "Llansamlet"),
    Station("LWM", "Llantwit Major"),
    Station("LNR", "Llanwrda"),
    Station("LNW", "Llanwrtyd"),
    Station("LLW", "Llwyngwril"),
    Station("LLY", "Llwynypia"),
    Station("LHA", "Loch Awe"),
    Station("LHE", "Loch Eil Outward Bound"),
    Station("LCL", "Lochailort"),
    Station("LCS", "Locheilside"),
    Station("LCG", "Lochgelly"),
    Station("LCC", "Lochluichart"),
    Station("LHW", "Lochwinnoch"),
    Station("LOC", "Lockerbie"),
    Station("LCK", "Lockwood"),
    Station("BFR", "London Blackfriars"),
    Station("LBG", "London Bridge"),
    Station("CST", "London Cannon Street"),
    Station("CHX", "London Charing Cross"),
    Station("EUS", "London Euston"),
    Station("FST", "London Fenchurch Street"),
    Station("LOF", "London Fields"),
    Station("KGX", "London Kings Cross"),
    Station("LST", "London Liverpool Street"),
    Station("MYB", "London Marylebone"),
    Station("PAD", "London Paddington"),
    Station("LRB", "London Road (Brighton)"),
    Station("LRD", "London Road (Guildford)"),
    Station("SPX", "London St Pancras (Intl)"),
    Station("STP", "London St Pancras International"),
    Station("VIC", "London Victoria"),
    Station("WAT", "London Waterloo"),
    Station("WAE", "London Waterloo East"),
    Station("LBK", "Long Buckby"),
    Station("LGE", "Long Eaton"),
    Station("LPR", "Long Preston"),
    Station("LGK", "Longbeck"),
    Station("LOB", "Longbridge"),
    Station("LNG", "Longcross"),
    Station("LGF", "Longfield"),
    Station("LND", "Longniddry"),
    Station("LPT", "Longport"),
    Station("LGN", "Longton"),
    Station("LOO", "Looe"),
    Station("LOT", "Lostock"),
    Station("LTG", "Lostock Gralam"),
    Station("LOH", "Lostock Hall"),
    Station("LOS", "Lostwithiel"),
    Station("LBO", "Loughborough"),
    Station("LGJ", "Loughborough Junction"),
    Station("LMR", "Low Moor"),
    Station("LOW", "Lowdham"),
    Station("LSY", "Lower Sydenham"),
    Station("LWT", "Lowestoft"),
    Station("LUD", "Ludlow"),
    Station("LUT", "Luton"),
    Station("LTN", "Luton Airport Parkway"),
    Station("LUX", "Luxulyan"),
    Station("LYD", "Lydney"),
    Station("LYE", "Lye (West Midlands)"),
    Station("LYP", "Lymington Pier"),
    Station("LYT", "Lymington Town"),
    Station("LYC", "Lympstone Commando"),
    Station("LYM", "Lympstone Village"),
    Station("LTM", "Lytham"),
    Station("MAC", "Macclesfield"),
    Station("MCN", "Machynlleth"),
    Station("MST", "Maesteg"),
    Station("MEW", "Maesteg (Ewenny Road)"),
    Station("MAG", "Maghull"),
    Station("MNS", "Maghull North"),
    Station("MDN", "Maiden Newton"),
    Station("MAI", "Maidenhead"),
    Station("MDB", "Maidstone Barracks"),
    Station("MDE", "Maidstone East"),
    Station("MDW", "Maidstone West"),
    Station("MAL", "Malden Manor"),
    Station("MLG", "Mallaig"),
    Station("MLT", "Malton"),
    Station("MVL", "Malvern Link"),
    Station("MIA", "Manchester Airport"),
    Station("MCO", "Manchester Oxford Road"),
    Station("MAN", "Manchester Piccadilly"),
    Station("MUF", "Manchester United Football Ground"),
    Station("MCV", "Manchester Victoria"),
    Station("MNE", "Manea"),
    Station("MNG", "Manningtree"),
    Station("MNP", "Manor Park"),
    Station("MNR", "Manor Road"),
    Station("MRB", "Manorbier"),
    Station("MAS", "Manors"),
    Station("MFT", "Mansfield"),
    Station("MSW", "Mansfield Woodhouse"),
    Station("MCH", "March"),
    Station("MRN", "Marden (Kent)"),
    Station("MAR", "Margate"),
    Station("MHR", "Market Harborough"),
    Station("MKR", "Market Rasen"),
    Station("MNC", "Markinch"),
    Station("MKT", "Marks Tey"),
    Station("MLW", "Marlow"),
    Station("MPL", "Marple"),
    Station("MSN", "Marsden (Yorks)"),
    Station("MSK", "Marske"),
    Station("MGN", "Marston Green"),
    Station("MTM", "Martin Mill"),
    Station("MAO", "Martins Heron"),
    Station("MTO", "Marton"),
    Station("MYH", "Maryhill"),
    Station("MYL", "Maryland"),
    Station("MRY", "Maryport"),
    Station("MAT", "Matlock"),
    Station("MTB", "Matlock Bath"),
    Station("MAU", "Mauldeth Road"),
    Station("MAX", "Maxwell Park"),
    Station("MAY", "Maybole"),
    Station("MZH", "Maze Hill"),
    Station("MHS", "Meadowhall"),
    Station("MEL", "Meldreth"),
    Station("MKM", "Melksham"),
    Station("MES", "Melton (Suffolk)"),
    Station("MMO", "Melton Mowbray"),
    Station("MEN", "Menheniot"),
    Station("MNN", "Menston"),
    Station("MEO", "Meols"),
    Station("MEC", "Meols Cop"),
    Station("MEP", "Meopham"),
    Station("MRW", "Meridian Water"),
    Station("MEY", "Merryton"),
    Station("MHM", "Merstham"),
    Station("MER", "Merthyr Tydfil"),
    Station("MEV", "Merthyr Vale"),
    Station("MGM", "Metheringham"),
    Station("MCE", "MetroCentre"),
    Station("MEX", "Mexborough"),
    Station("MIC", "Micheldever"),
    Station("MIK", "Micklefield"),
    Station("MBR", "Middlesbrough"),
    Station("MDL", "Middlewood"),
    Station("MDG", "Midgham"),
    Station("MLF", "Milford (Surrey)"),
    Station("MFH", "Milford Haven"),
    Station("MLH", "Mill Hill (Lancs)"),
    Station("MIL", "Mill Hill Broadway"),
    Station("MLB", "Millbrook (Beds)"),
    Station("MBK", "Millbrook (Hants)"),
    Station("MIN", "Milliken Park"),
    Station("MLM", "Millom"),
    Station("MIH", "Mills Hill (Manchester)"),
    Station("MLN", "Milngavie"),
    Station("MKC", "Milton Keynes Central"),
    Station("MFF", "Minffordd"),
    Station("MSR", "Minster"),
    Station("MIR", "Mirfield"),
    Station("MIS", "Mistley"),
    Station("MTC", "Mitcham Eastfields"),
    Station("MIJ", "Mitcham Junction"),
    Station("MOB", "Mobberley"),
    Station("MON", "Monifieth"),
    Station("MRS", "Monks Risborough"),
    Station("MTP", "Montpelier"),
    Station("MTS", "Montrose"),
    Station("MRF", "Moorfields"),
    Station("MOG", "Moorgate"),
    Station("MSD", "Moorside"),
    Station("MRP", "Moorthorpe"),
    Station("MRR", "Morar"),
    Station("MRD", "Morchard Road"),
    Station("MDS", "Morden South"),
    Station("MCM", "Morecambe"),
    Station("MTN", "Moreton (Dorset)"),
    Station("MRT", "Moreton (Merseyside)"),
    Station("MIM", "Moreton-in-Marsh"),
    Station("MFA", "Morfa Mawddach"),
    Station("MLY", "Morley"),
    Station("MPT", "Morpeth"),
    Station("MOR", "Mortimer"),
    Station("MTL", "Mortlake"),
    Station("MSS", "Moses Gate"),
    Station("MOS", "Moss Side"),
    Station("MSL", "Mossley (Manchester)"),
    Station("MSH", "Mossley Hill"),
    Station("MPK", "Mosspark"),
    Station("MSO", "Moston"),
    Station("MTH", "Motherwell"),
    Station("MOT", "Motspur Park"),
    Station("MTG", "Mottingham"),
    Station("DBG", "Mottisfont & Dunbridge"),
    Station("MLD", "Mouldsworth"),
    Station("MCB", "Moulsecoomb"),
    Station("MFL", "Mount Florida"),
    Station("MTV", "Mount Vernon"),
    Station("MTA", "Mountain Ash"),
    Station("MOO", "Muir of Ord"),
    Station("MUI", "Muirend"),
    Station("MUB", "Musselburgh"),
    Station("MYT", "Mytholmroyd"),
    Station("NFN", "Nafferton"),
    Station("NLS", "Nailsea & Backwell"),
    Station("NRN", "Nairn"),
    Station("NAN", "Nantwich"),
    Station("NAR", "Narberth"),
    Station("NBR", "Narborough"),
    Station("NVR", "Navigation Road"),
    Station("NTH", "Neath"),
    Station("NMT", "Needham Market"),
    Station("NEI", "Neilston"),
    Station("NEL", "Nelson"),
    Station("NES", "Neston"),
    Station("NET", "Netherfield"),
    Station("NRT", "Nethertown"),
    Station("NTL", "Netley"),
    Station("NBA", "New Barnet"),
    Station("NBC", "New Beckenham"),
    Station("NBN", "New Brighton"),
    Station("NCE", "New Clee"),
    Station("NWX", "New Cross"),
    Station("NXG", "New Cross Gate"),
    Station("NCK", "New Cumnock"),
    Station("NEH", "New Eltham"),
    Station("NHL", "New Holland"),
    Station("NHE", "New Hythe"),
    Station("NLN", "New Lane"),
    Station("NEM", "New Malden"),
    Station("NMC", "New Mills Central"),
    Station("NMN", "New Mills Newtown"),
    Station("NWM", "New Milton"),
    Station("NPD", "New Pudsey"),
    Station("NSG", "New Southgate"),
    Station("NCT", "Newark Castle"),
    Station("NNG", "Newark North Gate"),
    Station("NBE", "Newbridge"),
    Station("NBY", "Newbury"),
    Station("NRC", "Newbury Racecourse"),
    Station("NCL", "Newcastle"),
    Station("NCO", "Newcourt"),
    Station("NEW", "Newcraighall"),
    Station("NVH", "Newhaven Harbour"),
    Station("NVN", "Newhaven Town"),
    Station("NGT", "Newington"),
    Station("NMK", "Newmarket"),
    Station("NWE", "Newport (Essex)"),
    Station("NWP", "Newport (South Wales)"),
    Station("NQY", "Newquay"),
    Station("NSD", "Newstead"),
    Station("NTN", "Newton (Lanark)"),
    Station("NTA", "Newton Abbot"),
    Station("NAY", "Newton Aycliffe"),
    Station("NWN", "Newton for Hyde"),
    Station("NTC", "Newton St Cyres"),
    Station("NEG", "Newtongrange"),
    Station("NLW", "Newton-le-Willows"),
    Station("NWR", "Newtonmore"),
    Station("NOA", "Newton-on-Ayr"),
    Station("NWT", "Newtown (Powys)"),
    Station("NNP", "Ninian Park"),
    Station("NIT", "Nitshill"),
    Station("NBT", "Norbiton"),
    Station("NRB", "Norbury"),
    Station("NSB", "Normans Bay"),
    Station("NOR", "Normanton"),
    Station("NBW", "North Berwick"),
    Station("NCM", "North Camp"),
    Station("NDL", "North Dulwich"),
    Station("NFA", "North Fambridge"),
    Station("NLR", "North Llanrwst"),
    Station("NQU", "North Queensferry"),
    Station("NRD", "North Road (Darlington)"),
    Station("NSH", "North Sheen"),
    Station("NWA", "North Walsham"),
    Station("NWB", "North Wembley"),
    Station("NTR", "Northallerton"),
    Station("NMP", "Northampton"),
    Station("NFD", "Northfield"),
    Station("NFL", "Northfleet"),
    Station("NLT", "Northolt Park"),
    Station("NUM", "Northumberland Park"),
    Station("NWI", "Northwich"),
    Station("NRW", "Norwich"),
    Station("NWD", "Norwood Junction"),
    Station("NOT", "Nottingham"),
    Station("NUN", "Nuneaton"),
    Station("NHD", "Nunhead"),
    Station("NNT", "Nunthorpe"),
    Station("NUT", "Nutbourne"),
    Station("NUF", "Nutfield"),
    Station("OKN", "Oakengates"),
    Station("OKM", "Oakham"),
    Station("OKL", "Oakleigh Park"),
    Station("OBN", "Oban"),
    Station("OCK", "Ockendon"),
    Station("OLY", "Ockley"),
    Station("OKE", "Okehampton"),
    Station("OHL", "Old Hill"),
    Station("ORN", "Old Roan"),
    Station("OLD", "Old Street"),
    Station("OLF", "Oldfield Park"),
    Station("OLT", "Olton"),
    Station("ORE", "Ore"),
    Station("OMS", "Ormskirk"),
    Station("ORP", "Orpington"),
    Station("ORR", "Orrell"),
    Station("OPK", "Orrell Park"),
    Station("OTF", "Otford"),
    Station("OUN", "Oulton Broad North"),
    Station("OUS", "Oulton Broad South"),
    Station("OUT", "Outwood"),
    Station("OVE", "Overpool"),
    Station("OVR", "Overton"),
    Station("OXN", "Oxenholme Lake District"),
    Station("OXF", "Oxford"),
    Station("OXP", "Oxford Parkway"),
    Station("OXS", "Oxshott"),
    Station("OXT", "Oxted"),
    Station("PDW", "Paddock Wood"),
    Station("PDG", "Padgate"),
    Station("PGN", "Paignton"),
    Station("PCN", "Paisley Canal"),
    Station("PYG", "Paisley Gilmour Street"),
    Station("PYJ", "Paisley St James"),
    Station("PAL", "Palmers Green"),
    Station("PAN", "Pangbourne"),
    Station("PNL", "Pannal"),
    Station("PTF", "Pantyffynnon"),
    Station("PAR", "Par"),
    Station("PBL", "Parbold"),
    Station("PKT", "Park Street"),
    Station("PKS", "Parkstone (Dorset)"),
    Station("PSN", "Parson Street"),
    Station("PTK", "Partick"),
    Station("PRN", "Parton"),
    Station("PWY", "Patchway"),
    Station("PAT", "Patricroft"),
    Station("PTT", "Patterton"),
    Station("PEA", "Peartree"),
    Station("PMR", "Peckham Rye"),
    Station("PEG", "Pegswood"),
    Station("PEM", "Pemberton"),
    Station("PBY", "Pembrey & Burry Port"),
    Station("PMB", "Pembroke"),
    Station("PMD", "Pembroke Dock"),
    Station("PNA", "Penally"),
    Station("PEN", "Penarth"),
    Station("PCD", "Pencoed"),
    Station("PGM", "Pengam"),
    Station("PNE", "Penge East"),
    Station("PNW", "Penge West"),
    Station("PHG", "Penhelig"),
    Station("PNS", "Penistone"),
    Station("PKG", "Penkridge"),
    Station("PMW", "Penmaenmawr"),
    Station("PNM", "Penmere"),
    Station("PER", "Penrhiwceiber"),
    Station("PRH", "Penrhyndeudraeth"),
    Station("PNR", "Penrith (North Lakes)"),
    Station("PYN", "Penryn (Cornwall)"),
    Station("PES", "Pensarn (Gwynedd)"),
    Station("PHR", "Penshurst"),
    Station("PTB", "Pentre-Bach"),
    Station("PNY", "Pen-y-Bont"),
    Station("PNC", "Penychain"),
    Station("PNF", "Penyffordd"),
    Station("PNZ", "Penzance"),
    Station("PRW", "Perranwell"),
    Station("PRY", "Perry Barr"),
    Station("PSH", "Pershore"),
    Station("PTH", "Perth"),
    Station("PBO", "Peterborough"),
    Station("PTR", "Petersfield"),
    Station("PET", "Petts Wood"),
    Station("PEV", "Pevensey & Westham"),
    Station("PEB", "Pevensey Bay"),
    Station("PEW", "Pewsey"),
    Station("PIL", "Pilning"),
    Station("PIN", "Pinhoe"),
    Station("PIT", "Pitlochry"),
    Station("PSE", "Pitsea"),
    Station("PLS", "Pleasington"),
    Station("PLK", "Plockton"),
    Station("PLC", "Pluckley"),
    Station("PLM", "Plumley"),
    Station("PMP", "Plumpton"),
    Station("PLU", "Plumstead"),
    Station("PLY", "Plymouth"),
    Station("POK", "Pokesdown"),
    Station("PLG", "Polegate"),
    Station("PSW", "Polesworth"),
    Station("PWE", "Pollokshaws East"),
    Station("PWW", "Pollokshaws West"),
    Station("PLE", "Pollokshields East"),
    Station("PLW", "Pollokshields West"),
    Station("PMT", "Polmont"),
    Station("POL", "Polsloe Bridge"),
    Station("PON", "Ponders End"),
    Station("PTD", "Pontarddulais"),
    Station("PFR", "Pontefract Baghill"),
    Station("PFM", "Pontefract Monkhill"),
    Station("POT", "Pontefract Tanshelf"),
    Station("PLT", "Pontlottyn"),
    Station("PYC", "Pontyclun"),
    Station("PYP", "Pont-y-Pant"),
    Station("PPL", "Pontypool & New Inn"),
    Station("PPD", "Pontypridd"),
    Station("POO", "Poole"),
    Station("POP", "Poppleton"),
    Station("PTG", "Port Glasgow"),
    Station("PSL", "Port Sunlight"),
    Station("PTA", "Port Talbot Parkway"),
    Station("PTC", "Portchester"),
    Station("POR", "Porth"),
    Station("PTM", "Porthmadog"),
    Station("PLN", "Portlethen"),
    Station("PLD", "Portslade"),
    Station("PMS", "Portsmouth & Southsea"),
    Station("PMA", "Portsmouth Arms"),
    Station("PMH", "Portsmouth Harbour"),
    Station("PPK", "Possilpark & Parkhouse"),
    Station("PBR", "Potters Bar"),
    Station("PFY", "Poulton-le-Fylde"),
    Station("PYT", "Poynton"),
    Station("PRS", "Prees"),
    Station("PSC", "Prescot"),
    Station("PRT", "Prestatyn"),
    Station("PRB", "Prestbury"),
    Station("PRE", "Preston (Lancs)"),
    Station("PRP", "Preston Park"),
    Station("PST", "Prestonpans"),
    Station("PRA", "Prestwick International Airport"),
    Station("PTW", "Prestwick Town"),
    Station("PTL", "Priesthill & Darnley"),
    Station("PRR", "Princes Risborough"),
    Station("PRL", "Prittlewell"),
    Station("PRU", "Prudhoe"),
    Station("PUL", "Pulborough"),
    Station("PFL", "Purfleet"),
    Station("PUR", "Purley"),
    Station("PUO", "Purley Oaks"),
    Station("PUT", "Putney"),
    Station("PWL", "Pwllheli"),
    Station("PYE", "Pye Corner"),
    Station("PYL", "Pyle"),
    Station("QYD", "Quakers Yard"),
    Station("QBR", "Queenborough"),
    Station("QPK", "Queens Park (Glasgow)"),
    Station("QPW", "Queens Park (London)"),
    Station("QRP", "Queens Road (Peckham)"),
    Station("QRB", "Queenstown Road (Battersea)"),
    Station("QUI", "Quintrell Downs"),
    Station("RDF", "Radcliffe-on-Trent"),
    Station("RDT", "Radlett"),
    Station("RAD", "Radley"),
    Station("RDR", "Radyr"),
    Station("RNF", "Rainford"),
    Station("RNM", "Rainham (Essex)"),
    Station("RAI", "Rainham (Kent)"),
    Station("RNH", "Rainhill"),
    Station("RAM", "Ramsgate"),
    Station("RGW", "Ramsgreave & Wilpshire"),
    Station("RAN", "Rannoch"),
    Station("RAU", "Rauceby"),
    Station("RAV", "Ravenglass for Eskdale"),
    Station("RVB", "Ravensbourne"),
    Station("RVN", "Ravensthorpe"),
    Station("RWC", "Rawcliffe"),
    Station("RLG", "Rayleigh"),
    Station("RAY", "Raynes Park"),
    Station("RDG", "Reading"),
    Station("RDW", "Reading West"),
    Station("REC", "Rectory Road"),
    Station("RDB", "Redbridge"),
    Station("RBS", "Redcar British Steel"),
    Station("RCC", "Redcar Central"),
    Station("RCE", "Redcar East"),
    Station("RDN", "Reddish North"),
    Station("RDS", "Reddish South"),
    Station("RDC", "Redditch"),
    Station("RDH", "Redhill"),
    Station("RDA", "Redland"),
    Station("RED", "Redruth"),
    Station("REE", "Reedham (Norfolk)"),
    Station("RHM", "Reedham (Surrey)"),
    Station("REI", "Reigate"),
    Station("RTN", "Renton"),
    Station("RET", "Retford"),
    Station("RHI", "Rhiwbina"),
    Station("RIA", "Rhoose Cardiff International Airport"),
    Station("RHO", "Rhosneigr"),
    Station("RHL", "Rhyl"),
    Station("RHY", "Rhymney"),
    Station("RHD", "Ribblehead"),
    Station("RIL", "Rice Lane"),
    Station("RMD", "Richmond (London)"),
    Station("RIC", "Rickmansworth"),
    Station("RDD", "Riddlesdown"),
    Station("RID", "Ridgmont"),
    Station("RDM", "Riding Mill"),
    Station("RCA", "Risca & Pontymister"),
    Station("RIS", "Rishton"),
    Station("RBR", "Robertsbridge"),
    Station("RRN", "Robroyston"),
    Station("ROB", "Roby"),
    Station("RCD", "Rochdale"),
    Station("ROC", "Roche"),
    Station("RTR", "Rochester"),
    Station("RFD", "Rochford"),
    Station("RFY", "Rock Ferry"),
    Station("ROG", "Rogart"),
    Station("ROR", "Rogerstone"),
    Station("ROL", "Rolleston"),
    Station("RMB", "Roman Bridge"),
    Station("RMF", "Romford"),
    Station("RML", "Romiley"),
    Station("ROM", "Romsey"),
    Station("ROO", "Roose"),
    Station("RSG", "Rose Grove"),
    Station("RSH", "Rose Hill Marple"),
    Station("ROS", "Rosyth"),
    Station("RMC", "Rotherham Central"),
    Station("ROE", "Rotherhithe"),
    Station("RNR", "Roughton Road"),
    Station("RLN", "Rowlands Castle"),
    Station("ROW", "Rowley Regis"),
    Station("RYB", "Roy Bridge"),
    Station("RYN", "Roydon"),
    Station("RYS", "Royston"),
    Station("RUA", "Ruabon"),
    Station("RUF", "Rufford"),
    Station("RUG", "Rugby"),
    Station("RGT", "Rugeley Town"),
    Station("RGL", "Rugeley Trent Valley"),
    Station("RUN", "Runcorn"),
    Station("RUE", "Runcorn East"),
    Station("RKT", "Ruskington"),
    Station("RUS", "Ruswarp"),
    Station("RUT", "Rutherglen"),
    Station("RYD", "Ryde Esplanade"),
    Station("RYP", "Ryde Pier Head"),
    Station("RYR", "Ryde St Johns Road"),
    Station("RRB", "Ryder Brow"),
    Station("RYE", "Rye (Sussex)"),
    Station("RYH", "Rye House"),
    Station("SFD", "Salford Central"),
    Station("SLD", "Salford Crescent"),
    Station("SAF", "Salfords (Surrey)"),
    Station("SAH", "Salhouse"),
    Station("SAL", "Salisbury"),
    Station("SAE", "Saltaire"),
    Station("STS", "Saltash"),
    Station("SLB", "Saltburn"),
    Station("SLT", "Saltcoats"),
    Station("SAM", "Saltmarshe"),
    Station("SLW", "Salwick"),
    Station("SMC", "Sampford Courtenay"),
    Station("SNA", "Sandal & Agbrigg"),
    Station("SDB", "Sandbach"),
    Station("SNR", "Sanderstead"),
    Station("SDL", "Sandhills"),
    Station("SND", "Sandhurst (Berks)"),
    Station("SDG", "Sandling"),
    Station("SAN", "Sandown"),
    Station("SDP", "Sandplace"),
    Station("SAD", "Sandwell & Dudley"),
    Station("SDW", "Sandwich"),
    Station("SDY", "Sandy"),
    Station("SNK", "Sankey for Penketh"),
    Station("SQH", "Sanquhar"),
    Station("SRR", "Sarn"),
    Station("SDF", "Saundersfoot"),
    Station("SDR", "Saunderton"),
    Station("SAW", "Sawbridgeworth"),
    Station("SXY", "Saxilby"),
    Station("SAX", "Saxmundham"),
    Station("SCA", "Scarborough"),
    Station("SCT", "Scotscalder"),
    Station("SCH", "Scotstounhill"),
    Station("SCU", "Scunthorpe"),
    Station("SML", "Sea Mills"),
    Station("SEF", "Seaford (Sussex)"),
    Station("SFL", "Seaforth & Litherland"),
    Station("SEA", "Seaham"),
    Station("SEM", "Seamer"),
    Station("SSC", "Seascale"),
    Station("SEC", "Seaton Carew"),
    Station("SRG", "Seer Green & Jordans"),
    Station("SBY", "Selby"),
    Station("SRS", "Selhurst"),
    Station("SEL", "Sellafield"),
    Station("SEG", "Selling"),
    Station("SLY", "Selly Oak"),
    Station("SET", "Settle"),
    Station("SVK", "Seven Kings"),
    Station("SVS", "Seven Sisters"),
    Station("SEV", "Sevenoaks"),
    Station("SVB", "Severn Beach"),
    Station("STJ", "Severn Tunnel Junction"),
    Station("SDE", "Shadwell"),
    Station("SFR", "Shalford (Surrey)"),
    Station("SHN", "Shanklin"),
    Station("SFI", "Shawfair"),
    Station("SHW", "Shawford"),
    Station("SHL", "Shawlands"),
    Station("SSS", "Sheerness-on-Sea"),
    Station("SHF", "Sheffield"),
    Station("SED", "Shelford (Cambs)"),
    Station("SNF", "Shenfield"),
    Station("SEN", "Shenstone"),
    Station("SPB", "Shepherd's Bush"),
    Station("SPH", "Shepherds Well"),
    Station("SPY", "Shepley"),
    Station("SHP", "Shepperton"),
    Station("STH", "Shepreth"),
    Station("SHE", "Sherborne"),
    Station("SIE", "Sherburn-in-Elmet"),
    Station("SHM", "Sheringham"),
    Station("SLS", "Shettleston"),
    Station("SDM", "Shieldmuir"),
    Station("SFN", "Shifnal"),
    Station("SHD", "Shildon"),
    Station("SHI", "Shiplake"),
    Station("SHY", "Shipley (Yorks)"),
    Station("SPP", "Shippea Hill"),
    Station("SIP", "Shipton"),
    Station("SHB", "Shirebrook"),
    Station("SHH", "Shirehampton"),
    Station("SRO", "Shireoaks"),
    Station("SRL", "Shirley"),
    Station("SRY", "Shoeburyness"),
    Station("SHO", "Sholing"),
    Station("SDC", "Shoreditch High Street"),
    Station("SEH", "Shoreham (Kent)"),
    Station("SSE", "Shoreham-by-Sea"),
    Station("SRT", "Shortlands"),
    Station("SHT", "Shotton"),
    Station("SHS", "Shotts"),
    Station("SHR", "Shrewsbury"),
    Station("SID", "Sidcup"),
    Station("SIL", "Sileby"),
    Station("SIC", "Silecroft"),
    Station("SLK", "Silkstone Common"),
    Station("SLV", "Silver Street"),
    Station("SVR", "Silverdale"),
    Station("SIN", "Singer"),
    Station("SIT", "Sittingbourne"),
    Station("SKG", "Skegness"),
    Station("SKE", "Skewen"),
    Station("SKI", "Skipton"),
    Station("SGR", "Slade Green"),
    Station("SWT", "Slaithwaite"),
    Station("SLA", "Slateford"),
    Station("SLR", "Sleaford"),
    Station("SLH", "Sleights"),
    Station("SLO", "Slough"),
    Station("SMA", "Small Heath"),
    Station("SAB", "Smallbrook Junction"),
    Station("SGB", "Smethwick Galton Bridge"),
    Station("SMR", "Smethwick Rolfe Street"),
    Station("SMB", "Smithy Bridge"),
    Station("SNI", "Snaith"),
    Station("SDA", "Snodland"),
    Station("SWO", "Snowdown"),
    Station("SOR", "Sole Street"),
    Station("SOL", "Solihull"),
    Station("SYT", "Somerleyton"),
    Station("SAT", "South Acton"),
    Station("SBK", "South Bank"),
    Station("SBM", "South Bermondsey"),
    Station("SCY", "South Croydon"),
    Station("SES", "South Elmsall"),
    Station("SGN", "South Greenford"),
    Station("SGL", "South Gyle"),
    Station("SOH", "South Hampstead"),
    Station("SOK", "South Kenton"),
    Station("SMO", "South Merton"),
    Station("SOM", "South Milford"),
    Station("SRU", "South Ruislip"),
    Station("STO", "South Tottenham"),
    Station("SWS", "South Wigston"),
    Station("SOF", "South Woodham Ferrers"),
    Station("STL", "Southall"),
    Station("SOA", "Southampton Airport Parkway"),
    Station("SOU", "Southampton Central"),
    Station("SOB", "Southbourne"),
    Station("SBU", "Southbury"),
    Station("SEE", "Southease"),
    Station("SIA", "Southend Airport"),
    Station("SOC", "Southend Central"),
    Station("SOE", "Southend East"),
    Station("SOV", "Southend Victoria"),
    Station("SMN", "Southminster"),
    Station("SOP", "Southport"),
    Station("SWK", "Southwick"),
    Station("SOW", "Sowerby Bridge"),
    Station("SPA", "Spalding"),
    Station("SBR", "Spean Bridge"),
    Station("SPI", "Spital"),
    Station("SPO", "Spondon"),
    Station("SPN", "Spooner Row"),
    Station("SRI", "Spring Road"),
    Station("SPR", "Springburn"),
    Station("SPF", "Springfield"),
    Station("SQU", "Squires Gate"),
    Station("SAA", "St Albans Abbey"),
    Station("SAC", "St Albans City"),
    Station("SAR", "St Andrews Road"),
    Station("SAS", "St Annes-on-Sea"),
    Station("SAU", "St Austell"),
    Station("SBS", "St Bees"),
    Station("SBF", "St Budeaux Ferry Road"),
    Station("SBV", "St Budeaux Victoria Road"),
    Station("SCR", "St Columb Road"),
    Station("SDN", "St Denys"),
    Station("SER", "St Erth"),
    Station("SGM", "St Germans"),
    Station("SNH", "St Helens Central"),
    Station("SHJ", "St Helens Junction"),
    Station("SIH", "St Helier (Surrey)"),
    Station("SIV", "St Ives (Cornwall)"),
    Station("SJP", "St James Park (Exeter)"),
    Station("SJS", "St James Street (Walthamstow)"),
    Station("SAJ", "St Johns (London)"),
    Station("SKN", "St Keyne Wishing Well Halt"),
    Station("SLQ", "St Leonards Warrior Square"),
    Station("SMT", "St Margarets (Herts)"),
    Station("SMG", "St Margarets (London)"),
    Station("SMY", "St Mary Cray"),
    Station("STM", "St Michaels"),
    Station("SNO", "St Neots"),
    Station("STA", "Stafford"),
    Station("SNS", "Staines"),
    Station("SLL", "Stallingborough"),
    Station("SYB", "Stalybridge"),
    Station("SMD", "Stamford (Lincs)"),
    Station("SMH", "Stamford Hill"),
    Station("SFO", "Stanford-le-Hope"),
    Station("SNT", "Stanlow & Thornton"),
    Station("SSD", "Stansted Airport"),
    Station("SST", "Stansted Mountfitchet"),
    Station("SPU", "Staplehurst"),
    Station("SRD", "Stapleton Road"),
    Station("SBE", "Starbeck"),
    Station("SCS", "Starcross"),
    Station("SVL", "Staveley (Cumbria)"),
    Station("SCF", "Stechford"),
    Station("SON", "Steeton & Silsden"),
    Station("SPS", "Stepps"),
    Station("SVG", "Stevenage"),
    Station("STV", "Stevenston"),
    Station("SWR", "Stewartby"),
    Station("STT", "Stewarton"),
    Station("STG", "Stirling"),
    Station("SPT", "Stockport"),
    Station("SKS", "Stocksfield"),
    Station("SSM", "Stocksmoor"),
    Station("STK", "Stockton"),
    Station("SKM", "Stoke Mandeville"),
    Station("SKW", "Stoke Newington"),
    Station("SOT", "Stoke-on-Trent"),
    Station("SNE", "Stone (Staffs)"),
    Station("SCG", "Stone Crossing"),
    Station("SBP", "Stonebridge Park"),
    Station("SOG", "Stonegate"),
    Station("STN", "Stonehaven"),
    Station("SHU", "Stonehouse"),
    Station("SNL", "Stoneleigh"),
    Station("SBJ", "Stourbridge Junction"),
    Station("SBT", "Stourbridge Town"),
    Station("SOI", "Stow"),
    Station("SMK", "Stowmarket"),
    Station("STR", "Stranraer"),
    Station("SRA", "Stratford (London)"),
    Station("SFA", "Stratford International"),
    Station("SAV", "Stratford-upon-Avon"),
    Station("STY", "Stratford-upon-Avon Parkway"),
    Station("STC", "Strathcarron"),
    Station("STW", "Strawberry Hill"),
    Station("STE", "Streatham (Greater London)"),
    Station("SRC", "Streatham Common"),
    Station("SRH", "Streatham Hill"),
    Station("SHC", "Streethouse"),
    Station("SRN", "Strines"),
    Station("STF", "Stromeferry"),
    Station("SOO", "Strood (Kent)"),
    Station("STD", "Stroud (Gloucs)"),
    Station("STU", "Sturry"),
    Station("SYA", "Styal"),
    Station("SUD", "Sudbury & Harrow Road"),
    Station("SUY", "Sudbury (Suffolk)"),
    Station("SDH", "Sudbury Hill Harrow"),
    Station("SUG", "Sugar Loaf"),
    Station("SUM", "Summerston"),
    Station("SUU", "Sunbury"),
    Station("SUN", "Sunderland"),
    Station("SUP", "Sundridge Park"),
    Station("SNG", "Sunningdale"),
    Station("SNY", "Sunnymeads"),
    Station("SUR", "Surbiton"),
    Station("SQE", "Surrey Quays"),
    Station("SUO", "Sutton (Surrey)"),
    Station("SUT", "Sutton Coldfield"),
    Station("SUC", "Sutton Common"),
    Station("SPK", "Sutton Parkway"),
    Station("SWL", "Swale"),
    Station("SAY", "Swanley"),
    Station("SWM", "Swanscombe"),
    Station("SWA", "Swansea"),
    Station("SNW", "Swanwick"),
    Station("SWY", "Sway"),
    Station("SWG", "Swaythling"),
    Station("SWD", "Swinderby"),
    Station("SWI", "Swindon (Wilts)"),
    Station("SWE", "Swineshead"),
    Station("SNN", "Swinton (Manchester)"),
    Station("SWN", "Swinton (South Yorks)"),
    Station("SYD", "Sydenham (London)"),
    Station("SYH", "Sydenham Hill"),
    Station("SYL", "Syon Lane"),
    Station("SYS", "Syston"),
    Station("TAC", "Tackley"),
    Station("TAD", "Tadworth"),
    Station("TAF", "Taffs Well"),
    Station("TAI", "Tain"),
    Station("TAL", "Talsarnau"),
    Station("TLB", "Talybont"),
    Station("TLC", "Tal-y-Cafn"),
    Station("TAB", "Tame Bridge Parkway"),
    Station("TAM", "Tamworth"),
    Station("TAP", "Taplow"),
    Station("TAT", "Tattenham Corner"),
    Station("TAU", "Taunton"),
    Station("TAY", "Taynuilt"),
    Station("TED", "Teddington"),
    Station("TEA", "Tees-side Airport"),
    Station("TGM", "Teignmouth"),
    Station("TFC", "Telford Central"),
    Station("TMC", "Templecombe"),
    Station("TEN", "Tenby"),
    Station("TEY", "Teynham"),
    Station("THD", "Thames Ditton"),
    Station("THA", "Thatcham"),
    Station("THH", "Thatto Heath"),
    Station("THW", "The Hawthorns"),
    Station("TLK", "The Lakes (Warks)"),
    Station("THE", "Theale"),
    Station("TEO", "Theobalds Grove"),
    Station("TTF", "Thetford"),
    Station("THI", "Thirsk"),
    Station("TBY", "Thornaby"),
    Station("TNN", "Thorne North"),
    Station("TNS", "Thorne South"),
    Station("THO", "Thornford"),
    Station("THB", "Thornliebank"),
    Station("TNA", "Thornton Abbey"),
    Station("TTH", "Thornton Heath"),
    Station("THT", "Thorntonhall"),
    Station("TPB", "Thorpe Bay"),
    Station("TPC", "Thorpe Culvert"),
    Station("TLS", "Thorpe-le-Soken"),
    Station("TBD", "Three Bridges"),
    Station("TOK", "Three Oaks"),
    Station("THU", "Thurgarton"),
    Station("THC", "Thurnscoe"),
    Station("THS", "Thurso"),
    Station("TRS", "Thurston"),
    Station("TIL", "Tilbury Town"),
    Station("THL", "Tile Hill"),
    Station("TLH", "Tilehurst"),
    Station("TIP", "Tipton"),
    Station("TIR", "Tir-Phil"),
    Station("TIS", "Tisbury"),
    Station("TVP", "Tiverton Parkway"),
    Station("TOD", "Todmorden"),
    Station("TOL", "Tolworth"),
    Station("TPN", "Ton Pentre"),
    Station("TON", "Tonbridge"),
    Station("TDU", "Tondu"),
    Station("TNF", "Tonfanau"),
    Station("TNP", "Tonypandy"),
    Station("TOO", "Tooting"),
    Station("TOP", "Topsham"),
    Station("TQY", "Torquay"),
    Station("TRR", "Torre"),
    Station("TOT", "Totnes"),
    Station("TOM", "Tottenham Hale"),
    Station("TTN", "Totton"),
    Station("TWN", "Town Green"),
    Station("TRA", "Trafford Park"),
    Station("TRF", "Trefforest"),
    Station("TRE", "Trefforest Estate"),
    Station("TRH", "Trehafod"),
    Station("TRB", "Treherbert"),
    Station("TRY", "Treorchy"),
    Station("TRM", "Trimley"),
    Station("TRI", "Tring"),
    Station("TRD", "Troed-y-rhiw"),
    Station("TRN", "Troon"),
    Station("TRO", "Trowbridge"),
    Station("TRU", "Truro"),
    Station("TUL", "Tulloch"),
    Station("TUH", "Tulse Hill"),
    Station("TBW", "Tunbridge Wells"),
    Station("TUR", "Turkey Street"),
    Station("TUT", "Tutbury & Hatton"),
    Station("TWB", "Tweedbank"),
    Station("TWI", "Twickenham"),
    Station("TWY", "Twyford"),
    Station("TYC", "Ty Croes"),
    Station("TGS", "Ty Glas"),
    Station("TYG", "Tygwyn"),
    Station("TYL", "Tyndrum Lower"),
    Station("TYS", "Tyseley"),
    Station("TYW", "Tywyn"),
    Station("UCK", "Uckfield"),
    Station("UDD", "Uddingston"),
    Station("ULC", "Ulceby"),
    Station("ULL", "Ulleskelf"),
    Station("ULV", "Ulverston"),
    Station("UMB", "Umberleigh"),
    Station("UNI", "University (Birmingham)"),
    Station("UHA", "Uphall"),
    Station("UPL", "Upholland"),
    Station("UPM", "Upminster"),
    Station("UPH", "Upper Halliford"),
    Station("UHL", "Upper Holloway"),
    Station("UTY", "Upper Tyndrum"),
    Station("UWL", "Upper Warlingham"),
    Station("UPT", "Upton (Merseyside)"),
    Station("UPW", "Upwey"),
    Station("URM", "Urmston"),
    Station("UTT", "Uttoxeter"),
    Station("VAL", "Valley"),
    Station("VXH", "Vauxhall"),
    Station("VIR", "Virginia Water"),
    Station("WDO", "Waddon"),
    Station("WAD", "Wadhurst"),
    Station("WFL", "Wainfleet"),
    Station("WKK", "Wakefield Kirkgate"),
    Station("WKF", "Wakefield Westgate"),
    Station("WKD", "Walkden"),
    Station("WLG", "Wallasey Grove Road"),
    Station("WLV", "Wallasey Village"),
    Station("WLT", "Wallington"),
    Station("WAF", "Wallyford"),
    Station("WAM", "Walmer"),
    Station("WSL", "Walsall"),
    Station("WDN", "Walsden"),
    Station("WLC", "Waltham Cross"),
    Station("WHC", "Walthamstow Central"),
    Station("WMW", "Walthamstow Queen's Road"),
    Station("WAO", "Walton (Merseyside)"),
    Station("WAL", "Walton-on-Thames"),
    Station("WON", "Walton-on-the-Naze"),
    Station("WAN", "Wanborough"),
    Station("WSW", "Wandsworth Common"),
    Station("WWR", "Wandsworth Road"),
    Station("WNT", "Wandsworth Town"),
    Station("WNP", "Wanstead Park"),
    Station("WPE", "Wapping"),
    Station("WBL", "Warblington"),
    Station("WAR", "Ware (Herts)"),
    Station("WRM", "Wareham (Dorset)"),
    Station("WGV", "Wargrave"),
    Station("WMN", "Warminster"),
    Station("WNH", "Warnham"),
    Station("WBQ", "Warrington Bank Quay"),
    Station("WAC", "Warrington Central"),
    Station("WAW", "Warrington West"),
    Station("WRW", "Warwick"),
    Station("WRP", "Warwick Parkway"),
    Station("WTO", "Water Orton"),
    Station("WBC", "Waterbeach"),
    Station("WTR", "Wateringbury"),
    Station("WLO", "Waterloo (Merseyside)"),
    Station("WFH", "Watford High Street"),
    Station("WFJ", "Watford Junction"),
    Station("WFN", "Watford North"),
    Station("WTG", "Watlington"),
    Station("WAS", "Watton-at-Stone"),
    Station("WNG", "Waun-Gron Park"),
    Station("WAV", "Wavertree Technology Park"),
    Station("WED", "Wedgwood"),
    Station("WEE", "Weeley"),
    Station("WET", "Weeton"),
    Station("WMG", "Welham Green"),
    Station("WLI", "Welling"),
    Station("WEL", "Wellingborough"),
    Station("WLN", "Wellington (Shropshire)"),
    Station("WLP", "Welshpool"),
    Station("WGC", "Welwyn Garden City"),
    Station("WLW", "Welwyn North"),
    Station("WEM", "Wem"),
    Station("WMB", "Wembley Central"),
    Station("WCX", "Wembley Stadium"),
    Station("WMS", "Wemyss Bay"),
    Station("WND", "Wendover"),
    Station("WNN", "Wennington"),
    Station("WSA", "West Allerton"),
    Station("WBP", "West Brompton"),
    Station("WBY", "West Byfleet"),
    Station("WCL", "West Calder"),
    Station("WCY", "West Croydon"),
    Station("WDT", "West Drayton"),
    Station("WDU", "West Dulwich"),
    Station("WEA", "West Ealing"),
    Station("WEH", "West Ham"),
    Station("WHD", "West Hampstead"),
    Station("WHP", "West Hampstead Thameslink"),
    Station("WHR", "West Horndon"),
    Station("WKB", "West Kilbride"),
    Station("WKI", "West Kirby"),
    Station("WMA", "West Malling"),
    Station("WNW", "West Norwood"),
    Station("WRU", "West Ruislip"),
    Station("WRN", "West Runton"),
    Station("WLD", "West St Leonards"),
    Station("WSU", "West Sutton"),
    Station("WWI", "West Wickham"),
    Station("WWO", "West Worthing"),
    Station("WSB", "Westbury (Wilts)"),
    Station("WCF", "Westcliff"),
    Station("WCB", "Westcombe Park"),
    Station("WHA", "Westenhanger"),
    Station("WTA", "Wester Hailes"),
    Station("WFI", "Westerfield"),
    Station("WES", "Westerton"),
    Station("WGA", "Westgate-on-Sea"),
    Station("WHG", "Westhoughton"),
    Station("WNM", "Weston Milton"),
    Station("WSM", "Weston-super-Mare"),
    Station("WRL", "Wetheral"),
    Station("WYB", "Weybridge"),
    Station("WEY", "Weymouth"),
    Station("WBR", "Whaley Bridge"),
    Station("WHE", "Whalley (Lancs)"),
    Station("WTS", "Whatstandwell"),
    Station("WFF", "Whifflet"),
    Station("WHM", "Whimple"),
    Station("WNL", "Whinhill"),
    Station("WHN", "Whiston"),
    Station("WTB", "Whitby"),
    Station("WHT", "Whitchurch (Cardiff)"),
    Station("WCH", "Whitchurch (Hants)"),
    Station("WTC", "Whitchurch (Shropshire)"),
    Station("WHL", "White Hart Lane"),
    Station("WNY", "White Notley"),
    Station("ZLW", "Whitechapel"),
    Station("WCR", "Whitecraigs"),
    Station("WTH", "Whitehaven"),
    Station("WTL", "Whitland"),
    Station("WBD", "Whitley Bridge"),
    Station("WTE", "Whitlocks End"),
    Station("WHI", "Whitstable"),
    Station("WLE", "Whittlesea"),
    Station("WLF", "Whittlesford Parkway"),
    Station("WTN", "Whitton (London)"),
    Station("WWL", "Whitwell (Derbyshire)"),
    Station("WHY", "Whyteleafe"),
    Station("WHS", "Whyteleafe South"),
    Station("WCK", "Wick"),
    Station("WIC", "Wickford"),
    Station("WCM", "Wickham Market"),
    Station("WDD", "Widdrington"),
    Station("WID", "Widnes"),
    Station("WMR", "Widney Manor"),
    Station("WGN", "Wigan North Western"),
    Station("WGW", "Wigan Wallgate"),
    Station("WGT", "Wigton"),
    Station("WMI", "Wildmill"),
    Station("WIJ", "Willesden Junction"),
    Station("WLM", "Williamwood"),
    Station("WIL", "Willington"),
    Station("WMC", "Wilmcote"),
    Station("WML", "Wilmslow"),
    Station("WNE", "Wilnecote (Staffs)"),
    Station("WIM", "Wimbledon"),
    Station("WBO", "Wimbledon Chase"),
    Station("WSE", "Winchelsea"),
    Station("WIN", "Winchester"),
    Station("WNF", "Winchfield"),
    Station("WIH", "Winchmore Hill"),
    Station("WDM", "Windermere"),
    Station("WNC", "Windsor & Eton Central"),
    Station("WNR", "Windsor & Eton Riverside"),
    Station("WNS", "Winnersh"),
    Station("WTI", "Winnersh Triangle"),
    Station("WSF", "Winsford"),
    Station("WSH", "Wishaw"),
    Station("WTM", "Witham"),
    Station("WTY", "Witley"),
    Station("WTT", "Witton (West Midlands)"),
    Station("WVF", "Wivelsfield"),
    Station("WIV", "Wivenhoe"),
    Station("WOB", "Woburn Sands"),
    Station("WOK", "Woking"),
    Station("WKM", "Wokingham"),
    Station("WOH", "Woldingham"),
    Station("WVH", "Wolverhampton"),
    Station("WOL", "Wolverton"),
    Station("WOM", "Wombwell"),
    Station("WDE", "Wood End"),
    Station("WST", "Wood Street"),
    Station("WDB", "Woodbridge"),
    Station("WGR", "Woodgrange Park"),
    Station("WDL", "Woodhall"),
    Station("WDH", "Woodhouse"),
    Station("WDS", "Woodlesford"),
    Station("WLY", "Woodley"),
    Station("WME", "Woodmansterne"),
    Station("WSR", "Woodsmoor"),
    Station("WOO", "Wool"),
    Station("WLS", "Woolston"),
    Station("WWA", "Woolwich Arsenal"),
    Station("WWD", "Woolwich Dockyard"),
    Station("WWW", "Wootton Wawen"),
    Station("WOF", "Worcester Foregate Street"),
    Station("WCP", "Worcester Park"),
    Station("WOS", "Worcester Shrub Hill"),
    Station("WOP", "Worcestershire Parkway"),
    Station("WKG", "Workington"),
    Station("WRK", "Worksop"),
    Station("WOR", "Worle"),
    Station("WPL", "Worplesdon"),
    Station("WRT", "Worstead"),
    Station("WRH", "Worthing"),
    Station("WRB", "Wrabness"),
    Station("WRY", "Wraysbury"),
    Station("WRE", "Wrenbury"),
    Station("WRS", "Wressle"),
    Station("WXC", "Wrexham Central"),
    Station("WRX", "Wrexham General"),
    Station("WYE", "Wye"),
    Station("WYM", "Wylam"),
    Station("WYL", "Wylde Green"),
    Station("WMD", "Wymondham"),
    Station("WYT", "Wythall"),
    Station("YAL", "Yalding"),
    Station("YRD", "Yardley Wood"),
    Station("YRM", "Yarm"),
    Station("YAE", "Yate"),
    Station("YAT", "Yatton"),
    Station("YEO", "Yeoford"),
    Station("YVJ", "Yeovil Junction"),
    Station("YVP", "Yeovil Pen Mill"),
    Station("YET", "Yetminster"),
    Station("YNW", "Ynyswen"),
    Station("YOK", "Yoker"),
    Station("YRK", "York"),
    Station("YRT", "Yorton"),
    Station("YSM", "Ystrad Mynach"),
    Station("YSR", "Ystrad Rhondda"),
)
